Repository ita-social-projects/horondi_admin, pull requests merged in 2020-11, with the labels that each got.

#159 Sonarcloud quality gate
  src/components/contacts-form/contacts-form.js
  src/hooks/user/use-users-tabs.js
  src/pages/comments/comments.js
  src/pages/comments/index.js
  src/pages/home-page/home-page.js
  src/pages/home-page/index.js
  src/pages/material/material-color-palette/material-color-palette.js
  src/pages/material/material-details/material-details.js
  src/pages/products/product-edit/product-edit-form/product-edit-form.js
  src/pages/users/users-page/components/user-navbar/nav-filter-item/nav-filter-item.js
  src/pages/users/users-page/users-page.js
  src/redux/home/home.operations.js
  src/redux/home/home.reducer.js
  src/redux/orders/orders.reducer.js
  src/redux/orders/orders.sagas.js
  src/routes/routes.js
Labels: refactoring, special task

#153 added filtering by status on order-page
  src/configs/labels.js
  src/configs/titles.js
  src/pages/orders/orders-page/Status/Status.js
  src/pages/orders/orders-page/Status/order-status-styles.js
  src/pages/orders/orders-page/orders-page.js
  src/pages/orders/orders-page/orders-page.styles.js
  src/redux/orders/orders.operations.js
  src/redux/orders/orders.sagas.js
Labels: Task

#167 Homepage images test
  cypress.json
  cypress/integration/home.test.js
  package.json
  src/pages/home-page/__snapshots__/home-page.test.js.snap
  src/pages/home-page/home-page.js
  src/pages/home-page/home-page.test.js
  src/pages/products/product-edit/product-edit-form/product-carousel/product-carousel.js
  src/redux/home/home.actions.js
  src/redux/home/home.operations.js
  src/redux/home/tests/home.actions.test.js
  src/redux/home/tests/home.reducer.test.js
  src/redux/home/tests/home.sagas.test.js
  src/redux/home/tests/home.variables.js
  src/redux/model/model.operations.js
Labels: test

#169 Home page slider
  src/components/home-page-slide-form/home-page-slide-form.js
  src/components/home-page-slide-form/home-page-slide-form.styles.js
  src/components/home-page-slide-form/index.js
  src/configs/button-titles.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/menu-categories.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/index.css
  src/pages/home-page-slides/slide-add/index.js
  src/pages/home-page-slides/slide-add/slide-add.js
  src/pages/home-page-slides/slide-add/slide-add.styles.js
  src/pages/home-page-slides/slide-details/index.js
  src/pages/home-page-slides/slide-details/slide-details.js
  src/pages/home-page-slides/slide-details/slide-details.styles.js
  src/pages/home-page-slides/slides-order/index.js
  src/pages/home-page-slides/slides-order/slides-order.js
  src/pages/home-page-slides/slides-order/slides-order.styles.js
  src/pages/home-page-slides/slides-page/index.js
  src/pages/home-page-slides/slides-page/slides-page.js
  src/pages/home-page-slides/slides-page/slides-page.styles.js
  src/redux/home-page-slides/home-page-slides.actions.js
  src/redux/home-page-slides/home-page-slides.operations.js
  src/redux/home-page-slides/home-page-slides.reducer.js
  src/redux/home-page-slides/home-page-slides.sagas.js
  src/redux/home-page-slides/home-page-slides.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/routes/routes.js
  src/translations/home-page-slides.translations.js
  src/utils/use-home-page-slide-handlers.js
Labels: Task

#172 Delete categories tests
  cypress.json
  cypress/integration/categories/categories.test.js
  cypress/integration/categories/categories.variables.js
  cypress/support/commands.js
  debug.log
  src/components/dialog-window/dialog-window.js
  src/configs/labels.js
  src/configs/titles.js
  src/pages/categories/categories-page/categories.js
  src/pages/categories/categories-page/category-delete-dialog/category-delete-dialog.js
  src/pages/categories/categories-page/category-delete-dialog/category-delete-dialog.styles.js
  src/pages/categories/categories-page/category-delete-dialog/index.js
  src/pages/categories/categories-page/category-delete/category-delete.js
  src/pages/categories/categories-page/category-delete/category-delete.styles.js
  src/pages/categories/categories-page/category-delete/index.js
  src/pages/model/model-page/model-page.js
  src/redux/categories/categories.actions.js
  src/redux/categories/categories.operations.js
  src/redux/categories/categories.reducer.js
  src/redux/categories/categories.sagas.js
  src/redux/categories/categories.types.js
Labels: Task

#195 Removed subcategories from products
  src/components/buttons/delete-button/delete-button.js
  src/configs/labels.js
  src/containers/product-species-container/product-species-container.js
  src/pages/comments/comments.js
  src/pages/products/product-add/product-add-species/product-add-species.js
  src/pages/products/product-edit/product-edit-form/product-edit-form.js
  src/redux/products/products.operations.js
  src/redux/products/products.reducer.js
Labels: Task

#201 fixed orders status styling
  src/pages/orders/orders-page/Status/Status.js
Labels: bug

#204 Admin styles
  src/components/header-form/header-form.js
  src/configs/titles.js
  src/pages/business-pages/business-page-form/business-page-form.js
  src/pages/business-pages/business-page-form/business-page-form.styles.js
  src/pages/business-pages/business-page-list.js
  src/pages/business-pages/business-page-list.styles.js
  src/pages/categories/categories-add/categories-add.js
  src/pages/categories/categories-add/categories-add.styles.js
  src/pages/categories/categories-page/categories.js
  src/pages/categories/categories-page/categories.styles.js
  src/pages/comments/comments.js
  src/pages/comments/comments.style.js
  src/pages/common.styles.js
  src/pages/contacts-page/contacts-page.js
  src/pages/contacts-page/contacts-page.style.js
  src/pages/email-questions/email-questions-list.js
  src/pages/email-questions/email-questions-list.styles.js
  src/pages/header/header-page/header-page.js
  src/pages/header/header-page/header-page.styles.js
  src/pages/home-page-slides/slides-order/slides-order.js
  src/pages/home-page-slides/slides-order/slides-order.styles.js
  src/pages/home-page-slides/slides-page/slides-page.js
  src/pages/home-page-slides/slides-page/slides-page.styles.js
  src/pages/home-page/home-page.js
  src/pages/home-page/home-page.styles.js
  src/pages/home-page/tests/__snapshots__/home-page.test.js.snap
  src/pages/home-page/tests/home-page.test.js
  src/pages/material/material-page/material-page.js
  src/pages/material/material-page/material-page.styles.js
  src/pages/model/model-page/model-page.js
  src/pages/model/model-page/model-page.styles.js
  src/pages/news/news-page/news-page.js
  src/pages/news/news-page/news-page.styles.js
  src/pages/orders/orders-page/orders-page.js
  src/pages/orders/orders-page/orders-page.styles.js
  src/pages/pattern/pattern-page/pattern-page.js
  src/pages/products/products-page/products-nav/products-nav.js
  src/pages/products/products-page/products-page.js
  src/pages/products/products-page/products-page.styles.js
  src/pages/statistic/statistic-page.js
  src/pages/users/users-page/components/admin-tab/admin-tab.js
  src/pages/users/users-page/components/admin-tab/admin-tab.styles.js
  src/pages/users/users-page/users-page.js
Labels: refactoring

#198 Email questions
  src/configs/index.js
  src/configs/labels.js
  src/containers/products-filters-container/products-filters-container.js
  src/pages/email-questions/email-question-filter/email-question-filter.styles.js
  src/pages/email-questions/email-question-filter/email-questions-filter.js
  src/pages/email-questions/email-questions-list.js
  src/pages/email-questions/email-questions-list.styles.js
  src/pages/email-questions/operations-buttons/email-questions-operations-buttons.js
  src/utils/getTime.js
Labels: refactoring

#171 Implemented e2e tests for Users:
  .gitignore
  cypress/integration/user.test.js
  debug.log
  package.json
  src/pages/users/users-page/components/user-navbar/nav-filter-item/nav-filter-item.js
  src/pages/users/users-page/components/user-navbar/nav-sort/nav-sort.js
Labels: test

#218 add test for statistic sagas
  src/redux/selectors/stats.selectors.js
  src/redux/stats/stats.sagas.js
  src/redux/stats/tests/stats.saga.test.js
  src/redux/stats/tests/stats.variables.js
Labels: test

#221 add tests for patterns, orders and news sagas
  src/redux/news/tests/news-sagas.test.js
  src/redux/news/tests/news.variables.js
  src/redux/orders/orders.sagas.js
  src/redux/orders/test/orders-sagas.test.js
  src/redux/orders/test/orders.variables.js
  src/redux/pattern/pattern.sagas.js
  src/redux/pattern/tests/pattern.sagas.test.js
  src/redux/pattern/tests/pattern.variables.js
Labels: test

#220 Implement test for products saga
  src/redux/products/products.sagas.js
  src/redux/products/tests/products.saga.test.js
  src/redux/products/tests/products.variables.js
  src/redux/selectors/products.selectors.js
Labels: test

#217 email-questions action and reducer tests
  src/redux/email-questions/email-questions.sagas.js
  src/redux/email-questions/tests/email-questions.actions.test.js
  src/redux/email-questions/tests/email-questions.reducer.test.js
  src/redux/email-questions/tests/email-questions.sagas.test.js
  src/redux/email-questions/tests/email-questions.variables.js
Labels: test

#214 Write unit tests for users sagas
  package.json
  src/redux/selectors/users.selectors.js
  src/redux/users/tests/users-saga.test.js
  src/redux/users/tests/users.variables.js
  src/redux/users/users.saga.js
Labels: test

#222 Write test for model and material sagas
  src/redux/material/material.sagas.js
  src/redux/material/tests/material.saga.test.js
  src/redux/material/tests/material.variables.js
  src/redux/model/model.sagas.js
  src/redux/model/tests/model.saga.test.js
  src/redux/model/tests/model.variables.js
Labels: test

#199 Fix products filters
  src/configs/index.js
  src/configs/titles.js
  src/containers/products-filters-container/products-filters-container.js
  src/containers/products-filters-container/products-filters-container.styles.js
  src/pages/home-page-slides/slides-page/slides-page.js
  src/pages/orders/orders-page/orders-page.styles.js
  src/pages/products/products-page/products-nav/products-nav-clear-filters/products-nav-clear-filters.js
  src/pages/products/products-page/products-nav/products-nav-clear-filters/products-nav-clear-filters.styles.js
  src/pages/products/products-page/products-nav/products-nav-filters/products-nav-filters.js
  src/pages/products/products-page/products-nav/products-nav-search/products-nav-search.js
  src/pages/products/products-page/products-nav/products-nav-search/products-nav-search.styles.js
  src/pages/products/products-page/products-nav/products-nav-sort/products-nav-sort.js
  src/pages/products/products-page/products-nav/products-nav-sort/products-nav-sort.styles.js
  src/pages/products/products-page/products-nav/products-nav.js
  src/pages/products/products-page/products-nav/products-nav.styles.js
  src/translations/product.translations.js
Labels: refactoring
