Repository ita-social-projects/horondi_admin, pull requests merged in 2020-12, with the labels that each got.

#233 Order page style
  src/pages/orders/orders-page/orders-page.styles.js
Labels: refactoring

#228 write actions and reducer tests for users, products and model
  src/redux/model/tests/model.actions.test.js
  src/redux/model/tests/model.reducer.test.js
  src/redux/products/products.reducer.js
  src/redux/products/tests/products.actions.test.js
  src/redux/products/tests/products.reducer.test.js
  src/redux/products/tests/products.variables.js
  src/redux/users/tests/users.actions.test.js
  src/redux/users/tests/users.reducer.test.js
  src/redux/users/tests/users.variables.js
  src/redux/users/users.reducer.js
Labels: test

#238 add test for home page and home slides
  src/redux/error/error.reducer.js
  src/redux/error/tests/error.actions.test.js
  src/redux/error/tests/error.reducer.test.js
  src/redux/error/tests/error.variables.js
  src/redux/home-page-slides/home-page-slides.actions.js
  src/redux/home-page-slides/home-page-slides.sagas.js
  src/redux/home-page-slides/tests/home-page-slide.actions.test.js
  src/redux/home-page-slides/tests/home-page-slide.reducer.test.js
  src/redux/home-page-slides/tests/home-page-slide.saga.test.js
  src/redux/home-page-slides/tests/home-page-slide.variables.js
  src/redux/home/home.actions.js
  src/redux/home/home.reducer.js
  src/redux/home/home.sagas.js
  src/redux/home/tests/home.actions.test.js
  src/redux/home/tests/home.reducer.test.js
  src/redux/home/tests/home.sagas.test.js
  src/redux/home/tests/home.variables.js
Labels: test

#230 Error boundary: error information
  src/configs/statuses.js
  src/pages/error-page/error-page.js
  src/redux/error/error.reducer.js
  src/redux/root.reducer.js
Labels: refactoring

#215 Add go-back button
  package.json
  src/components/news-form/news-form.js
  src/configs/index.js
  src/configs/styles.js
  src/pages/categories/categories-add/categories-add.js
  src/pages/categories/categories-add/categories-add.styles.js
  src/pages/news/news-add/news-add.js
  src/pages/order-item/order-item.js
  src/pages/order-item/order-item.styles.js
  src/pages/products/product-add/products-add.js
  src/pages/products/product-add/products-add.styles.js
  src/pages/products/product-edit/product-edit-form/product-edit-form.js
  src/pages/products/product-edit/product-edit-form/product-edit-form.styles.js
  src/pages/users/users-details/users-details.js
  src/pages/users/users-details/users-details.styles.js
Labels: Task, refactoring

#242 fix:path
  package.json
  src/pages/order-item/order-item.js
Labels: refactoring

#244 fix:path #242
  src/components/news-form/news-form.js
  src/pages/news/news-add/news-add.js
  src/pages/products/product-add/products-add.js
  src/pages/products/product-edit/product-edit-form/product-edit-form.js
  src/pages/users/users-details/users-details.js
Labels: refactoring

#240 header tests
  src/redux/header/header.sagas.js
  src/redux/header/tests/header.actions.test.js
  src/redux/header/tests/header.reducer.test.js
  src/redux/header/tests/header.sagas.test.js
  src/redux/header/tests/header.variables.js
Labels: test

#245 add cypress test for statistic page
  cypress/integration/statistic/statistic.test.js
  cypress/integration/statistic/statistic.variables.js
  src/configs/index.js
  src/configs/labels.js
  src/pages/statistic/date-menu/date-menu.js
  src/pages/statistic/statistic-bar/statistic-bar.js
  src/pages/statistic/statistic-doughnut/legends-list/legends-list.js
  src/pages/statistic/statistic-doughnut/statistic-doughnut.js
  src/pages/statistic/statistic-page.js
Labels: test

#247 Labels refactoring
  cypress/integration/business-pages/business-pages.test.js
  src/components/header-form/header-form.js
  src/components/home-page-slide-form/home-page-slide-form.js
  src/components/material-form/material-form.js
  src/components/model-form/model-form.js
  src/components/news-form/news-form.js
  src/components/pattern-form/pattern-form.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/languages.js
  src/containers/product-info-container/product-info-container.js
  src/pages/business-pages/business-page-form/business-page-form.js
  src/pages/news/news-add/news-add.js
  src/utils/map-languages.js
Labels: Task

#234 Delete all button style + fix dialog bug
  src/components/buttons/delete-button/delete-button.js
  src/components/comments-section/comments-section.js
  src/components/dialog-window/dialog-window.js
  src/components/dialog-window/dialog-window.styles.js
  src/configs/button-titles.js
  src/pages/business-pages/business-page-list.js
  src/pages/categories/categories-add/categories-add.js
  src/pages/categories/categories-page/category-delete/category-delete.js
  src/pages/comments/comments.js
  src/pages/contacts-page/contacts-page.js
  src/pages/email-questions/email-questions-list.js
  src/pages/email-questions/operations-buttons/email-questions-operations-buttons.js
  src/pages/header/header-page/header-page.js
  src/pages/home-page-slides/slides-page/slides-page.js
  src/pages/material/material-color-palette/material-color-palette.js
  src/pages/material/material-page/material-page.js
  src/pages/model/model-page/model-page.js
  src/pages/news/news-page/news-page.js
  src/pages/pattern/pattern-page/pattern-page.js
  src/pages/users/users-page/users-page.js
  src/redux/dialog-window/dialog-window.reducer.js
  src/redux/dialog-window/tests/dialog-window.reducer.test.js
  src/utils/use-success-snackbar.js
Labels: refactoring

#281 Category
  cypress/integration/categories/categories.variables.js
  package-lock.json
  src/components/category-form/category-form.js
  src/components/category-form/category-form.styles.js
  src/components/category-form/index.js
  src/components/model-form/model-form.js
  src/configs/button-titles.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/table-head-row-titles.js
  src/containers/product-species-container/product-species-container.js
  src/pages/categories/categories-add/categories-add.js
  src/pages/categories/categories-add/categories-add.styles.js
  src/pages/categories/categories-add/index.js
  src/pages/categories/categories-details/categories-details.js
  src/pages/categories/categories-details/categories-details.styles.js
  src/pages/categories/categories-details/index.js
  src/pages/categories/categories-page/categories.js
  src/pages/categories/categories-page/categories.styles.js
  src/pages/categories/categories-page/category-delete-dialog/category-delete-dialog.styles.js
  src/pages/categories/categories-page/category-delete/category-delete.js
  src/pages/categories/categories-page/category-delete/category-delete.styles.js
  src/redux/categories/categories.actions.js
  src/redux/categories/categories.operations.js
  src/redux/categories/categories.reducer.js
  src/redux/categories/categories.sagas.js
  src/redux/categories/categories.types.js
  src/redux/categories/tests/categories.actions.test.js
  src/redux/categories/tests/categories.reducer.test.js
  src/redux/categories/tests/categories.sagas.test.js
  src/redux/categories/tests/category.variables.js
  src/redux/products/products.operations.js
  src/redux/products/tests/products.variables.js
  src/routes/routes.js
  src/translations/category.translations.js
  src/utils/use-category-handlers.js
Labels: priority: high, special task

#246 News page fix
  src/components/category-form/index.js
  src/components/editor/editor.js
  src/components/icons/customized-edit-icon/customized-edit-icon.js
  src/components/news-form/news-form.js
  src/components/news-form/news-form.styles.js
  src/configs/labels.js
  src/pages/categories/categories-add/categories-add.styles.js
  src/pages/categories/categories-page/categories.styles.js
  src/pages/model/model-details/model-details.js
  src/pages/news/news-add/index.js
  src/pages/news/news-add/news-add.js
  src/pages/news/news-add/news-add.styles.js
  src/pages/news/news-details/index.js
  src/pages/news/news-details/news-details.js
  src/pages/news/news-details/news-details.styles.js
  src/pages/news/news-form/index.js
  src/pages/news/news-form/news-form.js
  src/pages/news/news-form/news-form.styles.js
  src/pages/news/news-page/news-page.js
  src/redux/news/news.operations.js
  src/routes/routes.js
Labels: refactoring

#288 implement color functionality for material page
  package-lock.json
  package.json
  src/components/color-circle/color-circle.js
  src/components/color-circle/color-circle.styles.js
  src/components/color-circle/index.js
  src/components/colors-bar/color-bar.styles.js
  src/components/colors-bar/colors-bar.js
  src/components/colors-bar/index.js
  src/components/create-color/create-color.js
  src/components/create-color/create-color.styles.js
  src/components/create-color/index.js
  src/components/dialog-window-wrapper/dialog-window-wrapper.js
  src/components/dialog-window-wrapper/dialog-window-wrapper.styles.js
  src/components/dialog-window-wrapper/index.js
  src/components/material-form/material-form.js
  src/configs/button-titles.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/messages.js
  src/configs/pagination.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/pages/material/create-color/create-color.js
  src/pages/material/create-color/create-color.styles.js
  src/pages/material/material-color-palette/index.js
  src/pages/material/material-color-palette/material-color-palette-style.js
  src/pages/material/material-color-palette/material-color-palette.js
  src/pages/material/material-page/material-page.js
  src/pages/material/material-page/material-page.styles.js
  src/redux/color/color.actions.js
  src/redux/color/color.operations.js
  src/redux/color/color.reducer.js
  src/redux/color/color.sagas.js
  src/redux/color/color.types.js
  src/redux/material/material.actions.js
  src/redux/material/material.operations.js
  src/redux/material/material.reducer.js
  src/redux/material/material.sagas.js
  src/redux/material/material.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/selectors/color.selectors.js
  src/redux/selectors/material.selectors.js
  src/routes/routes.js
  src/translations/colors.translations.js
  src/utils/use-color-handlers.js
  src/utils/use-material-handlers.js
Labels: enhancement

#289 fix base change
  src/components/category-form/index.js
  src/components/editor/editor.js
  src/components/icons/customized-edit-icon/customized-edit-icon.js
  src/components/news-form/news-form.js
  src/components/news-form/news-form.styles.js
  src/configs/button-titles.js
  src/configs/labels.js
  src/pages/categories/categories-add/categories-add.styles.js
  src/pages/categories/categories-page/categories.styles.js
  src/pages/model/model-details/model-details.js
  src/pages/news/news-add/index.js
  src/pages/news/news-add/news-add.js
  src/pages/news/news-add/news-add.styles.js
  src/pages/news/news-details/index.js
  src/pages/news/news-details/news-details.js
  src/pages/news/news-details/news-details.styles.js
  src/pages/news/news-form/index.js
  src/pages/news/news-form/news-form.js
  src/pages/news/news-form/news-form.styles.js
  src/pages/news/news-page/news-page.js
  src/redux/news/news.operations.js
  src/redux/news/news.sagas.js
  src/redux/news/tests/news-sagas.test.js
  src/redux/news/tests/news.variables.js
  src/routes/routes.js
  src/utils/use-news-handlers.js
Labels: refactoring
