Repository ita-social-projects/horondi_admin, pull requests merged in 2020-10, with the labels that each got.

#100 User page refactor
  cypress/integration/user.test.js
  src/configs/index.js
  src/hooks/user/use-users-filtering.js
  src/hooks/user/use-users-handlers.js
  src/pages/users/register-user/register-user.js
  src/pages/users/users-details/users-details.js
  src/pages/users/users-page/components/admin-tab/admin-tab.js
  src/pages/users/users-page/components/admin-tab/admin-tab.styles.js
  src/pages/users/users-page/components/admin-tab/index.js
  src/pages/users/users-page/components/tab-panel/index.js
  src/pages/users/users-page/components/tab-panel/tab-panel.js
  src/pages/users/users-page/components/tab-panel/tab-panel.styles.js
  src/pages/users/users-page/components/user-tab/index.js
  src/pages/users/users-page/components/user-tab/user-tab.js
  src/pages/users/users-page/components/user-tab/user-tab.styles.js
  src/pages/users/users-page/users-page.js
  src/pages/users/users-page/users-page.styles.js
  src/redux/users/users.actions.js
  src/redux/users/users.operations.js
  src/redux/users/users.saga.js
Labels: refactoring

#117 Contacts redux tests
  src/redux/comments/comments.sagas.js
  src/redux/comments/tests/comments.actions.test.js
  src/redux/comments/tests/comments.reducer.test.js
  src/redux/comments/tests/comments.sagas.test.js
  src/redux/comments/tests/comments.variables.js
  src/redux/contact/contact.sagas.js
  src/redux/contact/tests/contact.actions.test.js
  src/redux/contact/tests/contact.reducer.test.js
  src/redux/contact/tests/contact.sagas.test.js
  src/redux/contact/tests/contact.variables.js
Labels: test

#121 Business pages redux tests
  src/redux/business-pages/business-pages.actions.js
  src/redux/business-pages/business-pages.reducer.js
  src/redux/business-pages/business-pages.sagas.js
  src/redux/business-pages/tests/business-pages.actions.test.js
  src/redux/business-pages/tests/business-pages.reducer.test.js
  src/redux/business-pages/tests/business-pages.sagas.test.js
  src/redux/business-pages/tests/business-pages.variables.js
Labels: test

#127 Order page reducer
  package.json
  src/configs/table-head-row-titles.js
  src/pages/orders/orders-page/orders-page.js
  src/pages/orders/orders-page/orders-page.styles.js
  src/redux/orders/orders.actions.js
  src/redux/orders/orders.operations.js
  src/redux/orders/orders.reducer.js
  src/redux/orders/orders.sagas.js
  src/redux/orders/orders.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
Labels: WIP

#113 Dialog window for admin registration
  cypress/integration/user.test.js
  cypress/support/commands.js
  debug.log
  src/configs/form-regexp.js
  src/configs/index.js
  src/configs/labels.js
  src/containers/form-dialog/components/dialog-content/dialog-content.js
  src/containers/form-dialog/components/dialog-content/dialog-content.styles.js
  src/containers/form-dialog/components/dialog-content/index.js
  src/containers/form-dialog/components/dialog-title/dialog-title.js
  src/containers/form-dialog/components/dialog-title/index.js
  src/containers/form-dialog/form-dialog.js
  src/containers/form-dialog/form-dialog.styles.js
  src/containers/form-dialog/index.js
  src/containers/table-container-generator/table-container-generator.js
  src/hooks/form-dialog/useFormDialog.js
  src/hooks/user/use-users-handlers.js
  src/pages/users/register-user/register-user.js
  src/pages/users/register-user/register-user.styles.js
  src/pages/users/users-details/containers/user-details-card/user-details-card.js
  src/pages/users/users-page/components/admin-tab/admin-tab.js
  src/pages/users/users-page/components/register-dialog/index.js
  src/pages/users/users-page/components/register-dialog/register-dialog.js
  src/pages/users/users-page/components/register-dialog/register-dialog.styles.js
  src/pages/users/users-page/components/tab-panel/index.js
  src/pages/users/users-page/components/tab-panel/tab-panel.js
  src/pages/users/users-page/components/user-tab/user-tab.js
  src/pages/users/users-page/users-page.js
  src/redux/users/users.operations.js
  src/routes/routes.js
Labels: enhancement

#125 Email questions
  package.json
  src/components/app/app.js
  src/components/dialog-window/dialog-window.js
  src/components/nav-menu/nav-menu.js
  src/configs/button-titles.js
  src/configs/detail-titles.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/menu-categories.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/containers/table-container-head/table-container-head.js
  src/containers/table-container-row/table-container-row.js
  src/pages/business-pages/business-page-list.js
  src/pages/email-questions/email-question-details/email-question-details.js
  src/pages/email-questions/email-question-details/email-question-details.styles.js
  src/pages/email-questions/email-question-details/index.js
  src/pages/email-questions/email-question-filter/email-questions-filter.js
  src/pages/email-questions/email-question-filter/index.js
  src/pages/email-questions/email-questions-list.js
  src/pages/email-questions/email-questions-list.styles.js
  src/pages/email-questions/index.js
  src/pages/email-questions/operations-buttons/email-questions-operations-buttons.js
  src/pages/email-questions/operations-buttons/email-questions-operations-buttons.styles.js
  src/pages/email-questions/operations-buttons/index.js
  src/redux/auth/auth.actions.js
  src/redux/auth/auth.operations.js
  src/redux/auth/auth.reducer.js
  src/redux/auth/auth.sagas.js
  src/redux/auth/auth.types.js
  src/redux/auth/tests/auth-sagas.test.js
  src/redux/categories/tests/categories.actions.test.js
  src/redux/dialog-window/dialog-window.reducer.js
  src/redux/dialog-window/tests/dialog-window.reducer.test.js
  src/redux/email-questions/email-questions.actions.js
  src/redux/email-questions/email-questions.operations.js
  src/redux/email-questions/email-questions.reducer.js
  src/redux/email-questions/email-questions.sagas.js
  src/redux/email-questions/email-questions.types.js
  src/redux/news/news.sagas.js
  src/redux/news/tests/news-sagas.test.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/routes/routes.js
  src/translations/email-questions.translations.js
  src/utils/getTime.js
  src/utils/use-success-snackbar.js
Labels: Task

#134 Home page edit
  src/components/contacts-form/contacts-form.js
  src/components/contacts-form/contacts-form.style.js
  src/configs/button-titles.js
  src/configs/menu-categories.js
  src/configs/routes.js
  src/configs/titles.js
  src/pages/home-page/home-page.js
  src/pages/home-page/home-page.styles.js
  src/pages/home-page/index.js
  src/redux/home/home.actions.js
  src/redux/home/home.operations.js
  src/redux/home/home.reducer.js
  src/redux/home/home.sagas.js
  src/redux/home/home.types.js
  src/redux/news/tests/news-reducer.test.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/routes/routes.js
  src/translations/home-page-edit.translations.js
Labels: Task

#139 User page enhancement - filtering,sorting,paginating and searching
  debug.log
  src/configs/button-titles.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/sort.js
  src/hooks/form-dialog/use-form-dialog.js
  src/hooks/user/use-users-filtering.js
  src/hooks/user/use-users-tabs.js
  src/pages/users/users-page/components/admin-tab/admin-tab.js
  src/pages/users/users-page/components/user-navbar/index.js
  src/pages/users/users-page/components/user-navbar/nav-clear-filters/index.js
  src/pages/users/users-page/components/user-navbar/nav-clear-filters/nav-clear-filters.js
  src/pages/users/users-page/components/user-navbar/nav-clear-filters/nav-clear-filters.styles.js
  src/pages/users/users-page/components/user-navbar/nav-filter-item/index.js
  src/pages/users/users-page/components/user-navbar/nav-filter-item/nav-filter-item.js
  src/pages/users/users-page/components/user-navbar/nav-filter-item/nav-filter-item.styles.js
  src/pages/users/users-page/components/user-navbar/nav-filters/index.js
  src/pages/users/users-page/components/user-navbar/nav-filters/nav-filters.js
  src/pages/users/users-page/components/user-navbar/nav-search/index.js
  src/pages/users/users-page/components/user-navbar/nav-search/nav-search.js
  src/pages/users/users-page/components/user-navbar/nav-search/nav-search.styles.js
  src/pages/users/users-page/components/user-navbar/nav-sort/index.js
  src/pages/users/users-page/components/user-navbar/nav-sort/nav-sort.js
  src/pages/users/users-page/components/user-navbar/nav-sort/nav-sort.styles.js
  src/pages/users/users-page/components/user-navbar/user-navbar.js
  src/pages/users/users-page/components/user-navbar/user-navbar.styles.js
  src/pages/users/users-page/components/user-tab/user-tab.js
  src/pages/users/users-page/users-page.js
  src/redux/users/users.actions.js
  src/redux/users/users.operations.js
  src/redux/users/users.reducer.js
  src/redux/users/users.saga.js
  src/redux/users/users.types.js
  src/translations/user.translations.js
Labels: enhancement

#140 Implement total stats
  src/configs/index.js
  src/configs/labels.js
  src/pages/statistic/statistic-bar/statistic-bar.js
  src/redux/stats/stats.operations.js
Labels: Task

#145 Quill and dialog window fixes
  src/components/buttons/delete-button/delete-button.js
  src/components/dialog-window/dialog-window.js
  src/components/editor/editor.js
  src/pages/business-pages/business-page-form/business-page-form.js
Labels: bug, refactoring, special task

#142 Order page
  package.json
  src/configs/button-titles.js
  src/configs/menu-categories.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/containers/table-container-row/table-container-row.js
  src/pages/email-questions/email-questions-list.js
  src/pages/orders/orders-page/index.js
  src/pages/orders/orders-page/orders-page.js
  src/pages/orders/orders-page/orders-page.styles.js
  src/redux/orders/orders.actions.js
  src/redux/orders/orders.operations.js
  src/redux/orders/orders.reducer.js
  src/redux/orders/orders.sagas.js
  src/redux/orders/orders.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/routes/routes.js
Labels: Task

#147 Material edit
  package.json
  src/components/material-form/material-form.js
  src/components/material-form/material-form.styles.js
  src/configs/button-titles.js
  src/configs/form-regexp.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/pages/material/create-color/create-color.js
  src/pages/material/material-color-palette/index.js
  src/pages/material/material-color-palette/material-color-palette-style.js
  src/pages/material/material-color-palette/material-color-palette.js
  src/pages/material/material-details/index.js
  src/pages/material/material-details/material-details.js
  src/pages/material/material-details/material-details.styles.js
  src/pages/material/material-page/material-page.js
  src/redux/material/material.actions.js
  src/redux/material/material.operations.js
  src/redux/material/material.reducer.js
  src/redux/material/material.sagas.js
  src/redux/material/material.types.js
  src/routes/routes.js
  src/utils/use-color-handlers.js
  src/utils/use-material-handlers.js
Labels: Task
