Repository ita-social-projects/horondi_admin, pull requests merged in 2021-11, with the labels that each got.

#1108 fix regex
  src/configs/form-regexp.js
Labels: bug, Admin

#1116 Fixed codesmells in admin buttons tests
  src/components/buttons/delete-button/delete-button.test.js
  src/components/buttons/save-button/save-button.test.js
  src/components/buttons/standard-button/standard-button.test.js
Labels: Admin

#1118 Hotfix/1115/codesmells and console errors in user-form component
  src/components/buttons/save-button/save-button.js
  src/components/filters-components/filter-radio-picker/component-filter-radio-picker.js
  src/components/filters-components/filter-single-picker/component-filter-single-picker.js
  src/components/forms/user-form/user-form.js
  src/components/icons/customized-edit-icon/edit-button.test.js
  src/configs/labels.js
  src/containers/image-upload-container/image-upload-container.js
  src/pages/users/user/user-details/user-details.js
Labels: Admin, Hotfix

#1120 Fixed routes in business pages
  src/configs/menu-categories.js
Labels: bug, Admin

#1122 Fix validations on news editing
  src/configs/form-regexp.js
Labels: bug, Admin

#1109 Bugfix/1107/pattern
  src/components/forms/pattern-form/pattern-form.js
Labels: bug, Admin

#1124 Remove validations from news updating form in Admin
  src/components/forms/news-form/news-form.js
Labels: refactoring, Admin
