Repository ita-social-projects/horondi_admin, pull requests merged in 2021-12, with the labels that each got.

#1134 Fix/1087/Save button on news editing page fix
  src/components/forms/news-form/news-form.js
  src/components/forms/news-form/tests/news-form.test.js
Labels: Admin, fix

#1135 Remove user role & rename the date
  src/components/filters/options-picker/options-picker.js
  src/components/filters/tests/filters.test.js
  src/configs/index.js
  src/configs/table-head-row-titles.js
Labels: Admin

#1142 Questions/answers/1140
  src/components/forms/questions-answers-form/index.js
  src/components/forms/questions-answers-form/questions-answers-form.js
  src/components/forms/questions-answers-form/tests/questions-answers-form.test.js
  src/components/forms/questions-answers-form/tests/questions-answers-form.variables.js
  src/configs/button-titles.js
  src/configs/labels.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/pages/business-pages/business-page-list.js
  src/pages/business-pages/tests/business-page-list.spec.js
  src/pages/business-pages/tests/mockBusinessPage.js
  src/redux/questions-answers/questions-answers.actions.js
  src/redux/questions-answers/questions-answers.operations.js
  src/redux/questions-answers/questions-answers.reducer.js
  src/redux/questions-answers/questions-answers.sagas.js
  src/redux/questions-answers/questions-answers.types.js
  src/redux/questions-answers/tests/questions-answers.actions.test.js
  src/redux/questions-answers/tests/questions-answers.reducer.test.js
  src/redux/questions-answers/tests/questions-answers.sagas.test.js
  src/redux/questions-answers/tests/questions-answers.variables.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/routes/routes.js
  src/utils/questions-answers-form.js
  src/utils/questions-answers-form.test.js
  src/utils/use-questions-answers-handlers.js
  src/utils/use-questions-answers.test.js
Labels: Admin

#1151 1143/React update process
  package.json
  src/setupTests.js
Labels: test, dependencies, Admin

#1153 1143/package-clearing
  package.json
  src/components/forms/model-form/tests/model-form.spec.js
  src/pages/home-page/tests/home-page.test.js
Labels: dependencies, Admin
