Repository ita-social-projects/horondi_admin, pull requests merged in 2021-01, with the labels that each got.

#294 Add constructor image upload for pattern
  src/components/pattern-form/pattern-form.js
  src/configs/error-messages.js
  src/configs/labels.js
  src/pages/pattern/pattern-details/pattern-details.js
  src/redux/pattern/pattern.operations.js
  src/utils/use-pattern-handlers.js
Labels: refactoring

#360 fix bug with exit dialog
  src/components/dialog-window/dialog-window.js
  src/components/nav-bar/nav-bar.js
  src/pages/categories/categories-page/category-delete/category-delete.js
  src/pages/email-questions/email-questions-list.js
  src/pages/email-questions/operations-buttons/email-questions-operations-buttons.js
  src/pages/home-page-slides/slides-page/slides-page.js
  src/pages/home-page/tests/home-page.test.js
  src/pages/material/material-color-palette/material-color-palette.js
  src/pages/material/material-page/material-page.js
  src/pages/order-item/order-item.js
  src/pages/products/product-edit/product-edit-form/product-carousel/product-carousel.js
  src/pages/products/product-edit/product-edit-form/product-edit-form.js
  src/pages/products/products-page/products-page.js
  src/pages/users/users-details/users-details.js
  src/redux/dialog-window/dialog-window.reducer.js
  src/redux/dialog-window/tests/dialog-window.reducer.test.js
  src/utils/use-success-snackbar.js
Labels: refactoring

#359 refactor news form
  src/configs/error-messages.js
  src/pages/news/news-add/index.js
  src/pages/news/news-add/news-add.js
  src/pages/news/news-details/index.js
  src/pages/news/news-details/news-details.js
  src/pages/news/news-form/news-form.js
  src/pages/news/news-form/news-form.styles.js
  src/redux/news/news.actions.js
  src/redux/news/news.reducer.js
  src/redux/news/news.sagas.js
  src/redux/news/news.types.js
  src/routes/routes.js
  src/utils/use-news-handlers.js
Labels: refactoring

#390 implement multiple colors adding to material
  src/components/colors-autocomplete/colors-autocomplete.js
  src/components/colors-autocomplete/colors-autocomplete.styles.js
  src/components/colors-autocomplete/index.js
  src/components/colors-bar/colors-bar.js
  src/components/material-form/material-form.js
  src/pages/material/material-details/material-details.js
  src/pages/material/material-page/material-page.js
  src/pages/material/material-page/material-page.styles.js
  src/redux/color/color.operations.js
  src/redux/material/material.operations.js
  src/utils/use-material-handlers.js
Labels: Admin, refactoring

#395 Fix pattern page
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/pattern-form/pattern-form.styles.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/configs/labels.js
  src/configs/styles.js
  src/pages/home-page-slides/slides-order/slides-order.js
  src/utils/use-pattern-handlers.js
Labels: Admin, WIP, bug, refactoring

#399 Lock NodeJS version
  .github/workflows/main.yml
  Dockerfile
  azure-pipelines.yml
Labels: devops

#408 News page fix
  src/components/forms/news-form/news-form.js
  src/pages/news/news-page.js
Labels: fix, refactoring

#402 Tests for colors in redux
  src/redux/color/tests/color.actions.test.js
  src/redux/color/tests/color.reducer.test.js
  src/redux/color/tests/color.sagas.test.js
  src/redux/color/tests/color.variables.js
Labels: Admin, test

#405 Bugfix/394
  src/configs/labels.js
  src/containers/product-info-container/product-info-container.js
  src/containers/product-species-container/product-species-container.js
  src/hooks/product/use-product-handlers.js
  src/hooks/product/use-product-species.js
  src/hooks/product/use-product-validation.js
  src/pages/products/product-add/product-add-options/index.js
  src/pages/products/product-add/product-add-options/product-add-options.js
  src/pages/products/product-add/product-add-species/product-add-species.js
  src/pages/products/product-add/products-add.js
  src/pages/products/product-edit/product-edit-form/product-edit-form.js
  src/pages/products/product-edit/product-edit.js
  src/pages/products/products-nav/products-nav-filters/products-nav-filters.js
  src/pages/products/products-page.js
  src/redux/products/products.actions.js
  src/redux/products/products.operations.js
  src/redux/products/products.reducer.js
  src/redux/products/products.sagas.js
  src/redux/products/products.types.js
  src/redux/products/tests/products.actions.test.js
  src/redux/products/tests/products.reducer.test.js
  src/redux/products/tests/products.saga.test.js
  src/redux/products/tests/products.variables.js
Labels: Database UI fix

#494 Regexp hotfix
  src/configs/form-regexp.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
Labels: Hotfix, UI
