Repository ita-social-projects/horondi_admin, pull requests merged in 2021-03, with the labels that each got.

#608 Wrote unit tests for 'StepperControlButtons' component #422
  src/components/buttons/stepper-control-buttons/tests/stepper-control-buttons.test.js
Labels: Admin, test

#616 fix translations
  src/components/forms/size-form/size-form.js
  src/configs/titles.js
Labels: Hotfix

#614 fix capitalise letters on pages #613
  src/containers/table-container-generator/table-container-generator.js
  src/containers/table-container-generator/table-container-generator.styles.js
Labels: Admin, fix

#611 Refactor/593
  src/pages/home-page-slides/slides-order/slides-order.js
  src/pages/model/constructor/constructor-page/constructor-page.js
  src/pages/statistic/statistic-page.js
  src/utils/constructor-page.js
  src/utils/slides-order.js
Labels: Admin, refactoring

#617 create test for comments redux #602
  src/redux/comments/comments.reducer.js
  src/redux/comments/tests/comments.actions.test.js
  src/redux/comments/tests/comments.reducer.test.js
  src/redux/comments/tests/comments.sagas.test.js
  src/redux/comments/tests/comments.variables.js
Labels: Admin, test

#615 Tests/603
  src/consts/method-types.js
  src/redux/sizes/tests/sizes.actions.test.js
  src/redux/sizes/tests/sizes.reducer.test.js
  src/redux/sizes/tests/sizes.sagas.test.js
  src/redux/sizes/tests/sizes.variables.js
Labels: Admin, test

#597 Feature/572
  src/assets/images/upload.png
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/pattern-form/pattern-form.styles.js
  src/configs/styles.js
  src/containers/image-upload-container/image-upload-patternContainer.js
  src/containers/image-upload-container/image-upload-patternContainer.styles.js
  src/utils/image-upload.js
Labels: Admin, refactoring

#620 Fixed a few more critical codesmells for Sonar #593
  src/components/create-color/create-color.js
  src/components/editor/clipboard/clipboard.js
  src/components/forms/business-page-form/business-page-form.js
  src/components/forms/category-form/category-form.js
  src/components/forms/contacts-form/contacts-form.js
  src/components/forms/material-form/material-form.js
  src/redux/comments/tests/comments.sagas.test.js
  src/utils/business-page-form.js
  src/utils/category-form.js
  src/utils/clipboard.js
  src/utils/contacts-form.js
  src/utils/create-color.js
  src/utils/material-form.js
Labels: Admin, refactoring

#649 Fixed. The 'font-family' and 'font-size' changed
  src/components/app/app-theme/typography.styles.js
  src/pages/main-page/main-page.styles.js
Labels: Admin, UI, bug

#641 fixed some bugs
  src/components/forms/model-form/model-form.js
  src/components/forms/model-form/model-form.styles.js
  src/configs/labels.js
  src/configs/styles.js
  src/redux/model/model.operations.js
Labels: Admin, fix

#657 Fixed login error message and category validation
  src/components/forms/category-form/category-form.js
  src/components/forms/category-form/category-form.styles.js
  src/components/forms/language-panel/language-panel.js
  src/configs/error-messages.js
  src/pages/login/login-page.js
  src/redux/auth/auth.sagas.js
Labels: Admin, bug, refactoring

#653 Added enzyme test for categories page
  src/pages/categories/tests/categories.test.js
  src/pages/categories/tests/variables.js
Labels: Admin, test

#652 Wrote Enzyme tests for Comment form #605
  src/components/forms/comment-form/tests/comment-form.test.js
  src/components/forms/comment-form/tests/comment-form.variables.js
Labels: Admin, test

#640 Removed the remaining cognitive complexity codesmells #593
  src/components/forms/model-form/model-form.js
  src/components/forms/news-form/news-form.js
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/product-form/product-form.js
  src/pages/email-questions/email-questions-list.js
  src/pages/home-page-slides/slides-order/slides-order.js
  src/pages/statistic/statistic-page.js
  src/utils/email-question-list.js
  src/utils/model-form.js
  src/utils/news-form.js
  src/utils/pattern-form.js
  src/utils/product-form.js
  src/utils/slides-order.js
  src/utils/statistic-page.js
Labels: Admin, Sonar, refactoring

#654 fixed initial values in the form
  src/configs/labels.js
  src/pages/contacts-page/contacts-edit/contacts-edit.js
Labels: Admin

#647 addet getRecentComment saga
  .github/pull_request_template.md
  src/redux/comments/comments.operations.js
  src/redux/comments/comments.sagas.js
Labels: Admin

#667 Update language panel
  src/components/forms/business-page-form/business-page-form.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/utils/business-page-form.js
  src/utils/use-business-handlers.js
Labels: Admin

#663 added enzyme tests for Sizes page
  src/pages/sizes/tests/mockStoreReturner.js
  src/pages/sizes/tests/sizes.test.js
Labels: Admin, test

#684 The button 'Зберегти' isn't clickable and error message doesn't appear
  src/components/forms/category-form/category-form.js
Labels: Admin, bug

#681 Added fields 'region' and 'district' to add order
  src/configs/regexes.js
  src/pages/order-item/tabs/delivery-details/ukrpost/ukrpost.js
  src/redux/orders/orders.operations.js
  src/redux/orders/orders.reducer.js
  src/utils/handle-orders-page.js
  src/utils/order.js
Labels: Admin
