Repository ita-social-projects/horondi_admin, pull requests merged in 2021-02, with the labels that each got.

#569 add purpose drop-down
  src/components/forms/material-form/material-form.js
  src/components/forms/material-form/material-form.styles.js
  src/configs/purpose-enum.js
Labels: Admin, Task

#570 fix admin material and pattern page
  src/components/forms/material-form/material-form.js
  src/components/forms/pattern-form/pattern-form.js
  src/pages/model/constructor/constructor-page/constructor-page.js
  src/pages/model/model-page.js
  src/pages/pattern/pattern-page.js
  src/redux/model/model.operations.js
  src/redux/pattern/pattern.operations.js
  src/redux/products/products.operations.js
Labels: Admin, bug

#568 Bugfix/394
  cypress/integration/business-pages/business-pages.variables.js
  cypress/integration/categories/categories.test.js
  src/components/forms/product-form/index.js
  src/components/forms/product-form/product-carousel/index.js
  src/components/forms/product-form/product-carousel/product-carousel.css
  src/components/forms/product-form/product-carousel/product-carousel.js
  src/components/forms/product-form/product-carousel/product-carousel.styles.js
  src/components/forms/product-form/product-form.js
  src/components/forms/product-form/product-form.styles.js
  src/configs/labels.js
  src/containers/product-materials-container/index.js
  src/containers/product-materials-container/product-materials-container.js
  src/containers/product-species-container/product-species-container.js
  src/hooks/product/use-product-handlers.js
  src/hooks/product/use-product-validation.js
  src/pages/products/product-add/product-add-images/product-add-images.js
  src/pages/products/product-add/product-add-info/index.js
  src/pages/products/product-add/product-add-info/product-add-info.js
  src/pages/products/product-add/product-add-price/index.js
  src/pages/products/product-add/product-add-price/product-add-price.js
  src/pages/products/product-add/product-add-species/index.js
  src/pages/products/product-add/product-add-species/product-add-species.js
  src/pages/products/product-add/product-add-species/product-add-species.styles.js
  src/pages/products/product-add/product-add-submit/index.js
  src/pages/products/product-add/product-add-submit/product-add-submit.js
  src/pages/products/product-add/product-add-submit/product-add-submit.styles.js
  src/pages/products/product-add/products-add.js
  src/pages/products/product-edit/product-edit-form/index.js
  src/pages/products/product-edit/product-edit-form/product-edit-form.js
  src/pages/products/product-edit/product-edit.js
  src/redux/products/products.actions.js
  src/redux/products/products.operations.js
  src/redux/products/products.reducer.js
  src/redux/products/products.sagas.js
  src/redux/products/products.types.js
  src/redux/products/tests/products.saga.test.js
  src/redux/products/tests/products.variables.js
  src/redux/selectors/products.selectors.js
  src/translations/product.translations.js
Labels: Database UI fix, Task

#573 add material input to drop-down on pattern page
  src/components/forms/material-form/material-form.js
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/pattern-form/pattern-form.styles.js
  src/configs/labels.js
  src/redux/material/material.actions.js
  src/redux/material/material.operations.js
  src/redux/material/material.reducer.js
  src/redux/material/material.sagas.js
  src/redux/material/material.types.js
Labels: Admin, Task

#571 Bugfix/394
  src/components/forms/product-form/product-form.js
  src/configs/labels.js
  src/containers/product-materials-container/product-materials-container.js
  src/containers/product-materials-container/product-materials-container.styles.js
  src/containers/product-species-container/product-species-container.js
  src/containers/shared.styles.js
  src/hooks/product/use-product-handlers.js
  src/hooks/product/use-product-validation.js
  src/redux/products/products.sagas.js
  src/redux/root.saga.js
  src/redux/selectors/products.selectors.js
  src/redux/snackbar/snackbar.actions.js
  src/redux/snackbar/snackbar.sagas.js
  src/redux/snackbar/snackbar.types.js
Labels: Database UI fix

#574 Created comment page on admin part
  src/components/comments-section/comments-section.js
  src/components/forms/product-form/product-form.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/pages/comments/comments.js
  src/pages/main-page/main-page.js
  src/redux/comments/comments.actions.js
  src/redux/comments/comments.operations.js
  src/redux/comments/comments.reducer.js
  src/redux/comments/comments.sagas.js
  src/redux/comments/comments.types.js
  src/redux/comments/tests/comments.actions.test.js
  src/redux/comments/tests/comments.reducer.test.js
  src/redux/comments/tests/comments.sagas.test.js
  src/redux/comments/tests/comments.variables.js
  src/redux/selectors/comments.selectors.js
Labels: Admin

#578 fix pattern form
  src/components/forms/pattern-form/pattern-form.js
Labels: Admin, bug

#577 rewrite upload images from base64 in database to link on blobStorage
  src/components/forms/constructor-form/constructor-form.js
  src/components/forms/pattern-form/pattern-form.js
  src/pages/model/constructor/constructor-page/constructor-page.js
  src/redux/constructor/constructor.operations.js
  src/redux/pattern/pattern.operations.js
  src/utils/use-constructor-handlers.js
  src/utils/use-pattern-handlers.js
Labels: Admin, refactoring

#583 Feature/581
  src/configs/button-titles.js
  src/configs/index.js
  src/configs/menu-categories.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/pages/sizes/index.js
  src/pages/sizes/sizes.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/selectors/sizes.selector.js
  src/redux/sizes/sizes.actions.js
  src/redux/sizes/sizes.operations.js
  src/redux/sizes/sizes.reducer.js
  src/redux/sizes/sizes.sagas.js
  src/redux/sizes/sizes.types.js
  src/routes/routes.js
Labels: Admin

#582 Implemented editing for comments.
  src/components/comments-section/comments-section.js
  src/components/forms/comment-form/comment-form.js
  src/components/forms/comment-form/comment-form.styles.js
  src/components/forms/comment-form/index.js
  src/components/forms/product-form/product-form.js
  src/components/forms/product-form/product-form.styles.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/routes.js
  src/pages/comments/comment-edit/comment-edit.js
  src/pages/comments/comment-edit/comment-edit.styles.js
  src/pages/comments/comment-edit/index.js
  src/pages/comments/comments.js
  src/pages/main-page/main-page.js
  src/pages/users/users-details/users-details.js
  src/redux/comments/comments.actions.js
  src/redux/comments/comments.operations.js
  src/redux/comments/comments.reducer.js
  src/redux/comments/comments.sagas.js
  src/redux/comments/comments.types.js
  src/routes/routes.js
  src/translations/comments.translations.js
Labels: Admin

#591 Hotfix/590
  src/hooks/product/use-product-species.js
  src/pages/products/products-nav/index.js
  src/pages/products/products-nav/products-nav-clear-filters/index.js
  src/pages/products/products-nav/products-nav-clear-filters/products-nav-clear-filters.js
  src/pages/products/products-nav/products-nav-clear-filters/products-nav-clear-filters.styles.js
  src/pages/products/products-nav/products-nav-filters/index.js
  src/pages/products/products-nav/products-nav-filters/products-nav-filters.js
  src/pages/products/products-nav/products-nav-filters/products-nav-filters.styles.js
  src/pages/products/products-nav/products-nav-search/index.js
  src/pages/products/products-nav/products-nav-search/products-nav-search.js
  src/pages/products/products-nav/products-nav-search/products-nav-search.styles.js
  src/pages/products/products-nav/products-nav-sort/index.js
  src/pages/products/products-nav/products-nav-sort/products-nav-sort.js
  src/pages/products/products-nav/products-nav-sort/products-nav-sort.styles.js
  src/pages/products/products-nav/products-nav.js
  src/pages/products/products-nav/products-nav.styles.js
  src/pages/products/products-page.js
  src/redux/products/products.operations.js
Labels: Admin, Hotfix, bug

#592 Add comment search
  src/hooks/filters/use-comment-filters.js
  src/pages/comments/comments.js
  src/pages/main-page/main-page.js
  src/redux/comments/comments.actions.js
  src/redux/comments/comments.operations.js
  src/redux/comments/comments.reducer.js
  src/redux/comments/comments.sagas.js
  src/redux/comments/comments.types.js
Labels: Admin

#589 Language panel for contacts
  src/components/forms/contacts-form/contacts-form.js
  src/components/forms/news-form/news-form.js
  src/configs/form-regexp.js
  src/configs/labels.js
Labels: Admin, UI

#594 Feature/565
  src/components/forms/size-form/index.js
  src/components/forms/size-form/size-form.js
  src/components/forms/size-form/size-form.styles.js
  src/configs/button-titles.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/material-ui-constants.js
  src/configs/messages.js
  src/configs/sizes-enum.js
  src/configs/titles.js
  src/pages/common.styles.js
  src/pages/sizes/sizes-add/index.js
  src/pages/sizes/sizes-add/size-add.js
  src/pages/sizes/sizes-add/size-add.styles.js
  src/pages/sizes/sizes-edit/index.js
  src/pages/sizes/sizes-edit/size-edit.js
  src/pages/sizes/sizes-edit/size-edit.styles.js
  src/pages/sizes/sizes.js
  src/redux/selectors/sizes.selector.js
  src/redux/sizes/sizes.actions.js
  src/redux/sizes/sizes.operations.js
  src/redux/sizes/sizes.reducer.js
  src/redux/sizes/sizes.sagas.js
  src/redux/sizes/sizes.types.js
  src/routes/routes.js
  src/translations/sizes.translations.js
  src/utils/size-helpers.js
  src/validations/sizes/size-form-validation.js
Labels: Admin

#585 Change language tabs to language panel on Homepage-slides page
  src/components/forms/home-page-slide-form/home-page-slide-form.js
  src/configs/labels.js
Labels: Admin, fix

#595 Order component fix
  src/configs/button-titles.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/messages.js
  src/configs/orders.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/pages/order-item/order-item.js
  src/pages/order-item/tabs/delivery-details.js
  src/pages/order-item/tabs/delivery.js
  src/pages/order-item/tabs/general.js
  src/pages/order-item/tabs/products.js
  src/pages/order-item/tabs/recipient.js
  src/pages/orders/Status/Status.js
  src/pages/orders/orders-page.js
  src/pages/orders/orders-page.styles.js
  src/redux/orders/orders.actions.js
  src/redux/orders/orders.operations.js
  src/redux/orders/orders.reducer.js
  src/redux/orders/orders.sagas.js
  src/redux/orders/orders.types.js
  src/redux/orders/test/orders.actions.test.js
  src/redux/orders/test/orders.variables.js
  src/routes/routes.js
  src/utils/order.js
Labels: Admin, dependencies

#599 Fix codesmells admin part
  src/components/buttons/delete-button/delete-button.js
  src/components/buttons/save-button/save-button.js
  src/components/buttons/save-button/save-button.test.js
  src/components/buttons/stepper-control-buttons/stepper-control-buttons.js
  src/components/color-circle/color-circle.js
  src/components/dialog-window/dialog-window.js
  src/components/editor/editor.js
  src/components/filter-search-sort/nav-clear-filters/nav-clear-filters.js
  src/components/filter-search-sort/nav-search/nav-search.js
  src/components/filter-search-sort/nav-sort/nav-sort.js
  src/components/icons/customized-delete-icon/customized-delete-icon.js
  src/containers/product-materials-container/product-materials-container.js
  src/containers/product-options-container/product-options-container.js
  src/containers/product-species-container/product-species-container.js
  src/containers/table-container-row/table-container-row.js
  src/pages/email-questions/email-question-filter/email-questions-filter.js
  src/pages/email-questions/operations-buttons/email-questions-operations-buttons.js
  src/pages/order-item/order-item.js
  src/redux/dialog-window/dialog-window.reducer.js
  src/redux/dialog-window/tests/dialog-window.reducer.test.js
  src/utils/use-category-handlers.js
  src/utils/use-color-handlers.js
  src/utils/use-header-handlers.js
  src/utils/use-home-page-slide-handlers.js
  src/utils/use-material-handlers.js
  src/utils/use-model-handlers.js
  src/utils/use-news-handlers.js
Labels: Admin

#607 fix codesmells on admin part
  src/components/buttons/delete-button/delete-button.js
  src/components/buttons/save-button/save-button.js
  src/components/buttons/save-button/save-button.test.js
  src/components/buttons/stepper-control-buttons/stepper-control-buttons.js
  src/components/color-circle/color-circle.js
  src/components/dialog-window/dialog-window.js
  src/components/editor/editor.js
  src/components/filter-search-sort/nav-clear-filters/nav-clear-filters.js
  src/components/filter-search-sort/nav-search/nav-search.js
  src/components/filter-search-sort/nav-sort/nav-sort.js
  src/components/icons/customized-delete-icon/customized-delete-icon.js
  src/containers/product-materials-container/product-materials-container.js
  src/containers/product-options-container/product-options-container.js
  src/containers/product-species-container/product-species-container.js
  src/containers/table-container-row/table-container-row.js
  src/pages/email-questions/email-question-filter/email-questions-filter.js
  src/pages/email-questions/operations-buttons/email-questions-operations-buttons.js
  src/pages/order-item/order-item.js
  src/redux/dialog-window/dialog-window.reducer.js
  src/redux/dialog-window/tests/dialog-window.reducer.test.js
Labels: Admin
