Repository ita-social-projects/horondi_admin, pull requests merged in 2021-07, with the labels that each got.

#814 Added filters to pattern page
  package-lock.json
  src/components/filter-search-sort/filter-by-date/filter-by-date.styles.js
  src/components/filter-search-sort/filter-by-date/nav-filter-by-date.js
  src/configs/button-titles.js
  src/consts/pattern-status.js
  src/hooks/filters/use-order-filters.js
  src/hooks/filters/use-pattern-filters.js
  src/pages/pattern/pattern-page.js
  src/pages/pattern/tests/__snapshots__/pattern-page.test.js.snap
  src/pages/pattern/tests/pattern-page.test.js
  src/redux/pattern/pattern.actions.js
  src/redux/pattern/pattern.operations.js
  src/redux/pattern/pattern.reducer.js
  src/redux/pattern/pattern.types.js
  src/redux/pattern/tests/pattern.reducer.test.js
  src/utils/pattern.js
Labels: Admin

#835 fix prop types in product form
  src/components/filter-search-sort/filter-by-multiple-values/nav-filter-by-values.js
  src/components/filter-search-sort/filter-navbar.js
  src/components/filter-search-sort/nav-clear-filters/nav-clear-filters.js
  src/components/filter-search-sort/nav-search/nav-search.js
  src/components/filter-search-sort/nav-sort/nav-sort.js
  src/components/forms/language-panel/language-panel.js
  src/containers/product-info-container/product-info-container.js
  src/containers/product-materials-container/product-materials-container.js
  src/containers/product-species-container/product-species-container.js
  src/pages/products/product-add/product-add-images/product-add-images.js
Labels: refactoring

#855 add photos of new group members
  README.md
Labels: Admin

#862 Created new component POCKETS (CRUD)
  src/components/forms/pockets-form/index.js
  src/components/forms/pockets-form/pockets-form.js
  src/components/forms/pockets-form/pockets-form.styles.js
  src/configs/button-titles.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/menu-categories.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/consts/history-actions.js
  src/hooks/filters/use-pocket-filters.js
  src/pages/pockets/index.js
  src/pages/pockets/pockets-add/index.js
  src/pages/pockets/pockets-add/pockets-add.js
  src/pages/pockets/pockets-add/pockets-add.styles.js
  src/pages/pockets/pockets-edit/index.js
  src/pages/pockets/pockets-edit/pockets-edit.js
  src/pages/pockets/pockets-edit/pockets-edit.styles.js
  src/pages/pockets/pockets-page.js
  src/pages/pockets/pockets-page.styles.js
  src/redux/pockets/pockets.actions.js
  src/redux/pockets/pockets.operations.js
  src/redux/pockets/pockets.reducer.js
  src/redux/pockets/pockets.sagas.js
  src/redux/pockets/pockets.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/selectors/pockets.selectors.js
  src/routes/routes.js
  src/translations/pockets.translations.js
  src/utils/pockets-form.js
  src/utils/use-pockets-handlers.js
Labels: Admin, constructor

#869 (SP:3) Write enzyme test for LanguagePanel component #446
  src/components/forms/language-panel/tests/language-panel.test.js
  src/components/forms/language-panel/tests/language-panel.variables.js
Labels: Admin, test

#844 Refactoring form buttons #706
  src/components/forms/business-page-form/business-page-form.js
  src/components/forms/business-page-form/business-page-form.styles.js
  src/components/forms/category-form/category-form.js
  src/components/forms/category-form/category-form.styles.js
  src/components/forms/comment-form/comment-form.js
  src/components/forms/comment-form/comment-form.styles.js
  src/components/forms/comment-form/tests/comment-form.test.js
  src/components/forms/contacts-form/contacts-form.js
  src/components/forms/contacts-form/contacts-form.style.js
  src/components/forms/header-form/header-form.js
  src/components/forms/header-form/header-form.styles.js
  src/components/forms/home-page-slide-form/home-page-slide-form.js
  src/components/forms/home-page-slide-form/home-page-slide-form.styles.js
  src/components/forms/material-form/material-form.js
  src/components/forms/material-form/material-form.styles.js
  src/components/forms/model-form/model-form.js
  src/components/forms/model-form/model-form.styles.js
  src/components/forms/news-form/news-form.js
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/pattern-form/pattern-form.styles.js
  src/components/forms/product-form/product-form.js
  src/components/forms/product-form/product-form.styles.js
  src/components/forms/size-form/size-form.js
  src/components/forms/size-form/size-form.styles.js
  src/configs/styles.js
  src/pages/categories/categories-add/categories-add.styles.js
  src/pages/categories/categories-details/categories-details.styles.js
  src/pages/comments/comment-edit/comment-edit.styles.js
  src/pages/header/header-add/header-add.styles.js
  src/pages/header/header-details/header-details.styles.js
  src/pages/history/history-details/history-details.js
  src/pages/history/history-details/history-details.styles.js
  src/pages/home-page-slides/slide-add/slide-add.styles.js
  src/pages/home-page-slides/slide-details/slide-details.styles.js
  src/pages/material/material-add/material-add.styles.js
  src/pages/model/model-add/model-add.styles.js
  src/pages/model/model-details/model-details.styles.js
  src/pages/order-item/order-item.js
  src/pages/order-item/order-item.styles.js
  src/pages/pattern/pattern-add/pattern-add.js
  src/pages/pattern/pattern-add/pattern-add.styles.js
  src/pages/pattern/pattern-details/pattern-details.styles.js
  src/pages/sizes/sizes-add/size-add.styles.js
  src/pages/sizes/sizes-edit/size-edit.styles.js
Labels: Admin, refactoring

#870 (SP: 5)Write enzyme test for NewsForm component #449
  src/components/forms/news-form/tests/news-form.test.js
  src/components/forms/news-form/tests/news-form.variables.js
Labels: Admin, test

#890 fix styles pockets-form
  src/components/forms/pockets-form/pockets-form.js
  src/components/forms/pockets-form/pockets-form.styles.js
  src/utils/pockets-form.js
Labels: Admin, constructor

#892 Update Back form and page add filters and fixed bugs
  src/components/forms/back-form/back-form.js
  src/components/forms/back-form/back-form.styles.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/configs/labels.js
  src/configs/messages.js
  src/configs/purpose-enum.js
  src/configs/table-head-row-titles.js
  src/containers/back-materials-container/back-materials-container.js
  src/containers/back-materials-container/back-materials-container.styles.js
  src/containers/back-materials-container/index.js
  src/hooks/filters/use-back-filters.js
  src/pages/back/back-add/back-add.js
  src/pages/back/back-add/back-add.styles.js
  src/pages/back/back-details/back-details.js
  src/pages/back/back-details/back-details.styles.js
  src/pages/back/back-page.js
  src/redux/back/back.actions.js
  src/redux/back/back.operations.js
  src/redux/back/back.reducer.js
  src/redux/back/back.sagas.js
  src/redux/back/back.types.js
  src/redux/products/products.operations.js
  src/translations/material.translations.js
  src/utils/back-form.js
  src/utils/use-back-handlers.js
Labels: Admin

#838 Added constructot list page
  src/components/forms/back-form/back-form.js
  src/components/forms/constructor-form/constructor-form.styles.js
  src/components/forms/constructor-form/constructor-model-form.js
  src/components/forms/constructor-form/constructor-model-form.styles.js
  src/configs/button-titles.js
  src/configs/menu-categories.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/titles.js
  src/pages/constructor-list/constructor-details/constructor-details.js
  src/pages/constructor-list/constructor-details/constructor-details.styles.js
  src/pages/constructor-list/constructor-details/index.js
  src/pages/constructor-list/constructor-list-page.js
  src/pages/constructor-list/constructor-list-page.styles.js
  src/pages/constructor-list/index.js
  src/pages/model/constructor/constructor-page/constructor-page.js
  src/routes/routes.js
Labels: Admin

#893 Add eslint to ci
  .github/workflows/main.yml
Labels: Admin, devops

#908 New functionality 'Position Component' for Constructor/pockets
  src/components/forms/pockets-form/pockets-form.js
  src/components/forms/position-form/index.js
  src/components/forms/position-form/position-form.js
  src/components/forms/position-form/position-form.styles.js
  src/configs/button-titles.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/menu-categories.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/consts/history-actions.js
  src/hooks/filters/use-position-filters.js
  src/pages/pockets/pockets-page.js
  src/pages/position/index.js
  src/pages/position/position-add/index.js
  src/pages/position/position-add/position-add.js
  src/pages/position/position-edit/index.js
  src/pages/position/position-edit/position-edit.js
  src/pages/position/position-page.js
  src/redux/position/position.actions.js
  src/redux/position/position.operations.js
  src/redux/position/position.reducer.js
  src/redux/position/position.sagas.js
  src/redux/position/position.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/selectors/position.selectors.js
  src/routes/routes.js
  src/utils/position-form.js
  src/utils/use-position-handlers.js
Labels: Admin

#912 Created closure page and form
  src/components/forms/closures-form/closures-form.js
  src/components/forms/closures-form/closures-form.styles.js
  src/components/forms/closures-form/index.js
  src/components/forms/position-form/index.js
  src/configs/button-titles.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/menu-categories.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/consts/history-actions.js
  src/hooks/filters/use-closure-filters.js
  src/pages/closures/closures-add/closures-add.js
  src/pages/closures/closures-add/closures-add.styles.js
  src/pages/closures/closures-add/index.js
  src/pages/closures/closures-edit/closures-edit.js
  src/pages/closures/closures-edit/closures-edit.styles.js
  src/pages/closures/closures-edit/index.js
  src/pages/closures/closures-page.js
  src/pages/closures/closures-page.styles.js
  src/pages/closures/index.js
  src/redux/back/back.actions.js
  src/redux/back/back.reducer.js
  src/redux/back/back.types.js
  src/redux/closures/closures.actions.js
  src/redux/closures/closures.operations.js
  src/redux/closures/closures.reducer.js
  src/redux/closures/closures.sagas.js
  src/redux/closures/closures.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/selectors/closures.selectors.js
  src/routes/routes.js
  src/translations/closures.translations.js
  src/utils/closures-form.js
  src/utils/use-closures-handlers.js
Labels: Admin

#919 Implemented positions into pockets
  src/components/forms/model-form/model-form.js
  src/components/forms/pockets-form/pockets-form.js
  src/components/forms/pockets-form/pockets-form.styles.js
  src/configs/error-messages.js
  src/configs/labels.js
  src/configs/menu-categories.js
  src/configs/styles.js
  src/redux/pockets/pockets.actions.js
  src/redux/pockets/pockets.operations.js
  src/redux/pockets/pockets.reducer.js
  src/redux/pockets/pockets.types.js
  src/redux/position/position.actions.js
  src/redux/position/position.operations.js
  src/redux/position/position.reducer.js
  src/redux/position/position.types.js
  src/utils/pockets-form.js
  src/utils/use-pockets-handlers.js
Labels: Admin, constructor

#918 bug fixed / Responsive design for Product form#872
  src/components/forms/product-form/product-form.styles.js
Labels: Admin, bug

#833 [Cтворити гобелен] Error messages that mandatory fields are filled in with to long values is not shown Fixbug/795
  src/components/forms/pattern-form/pattern-form.js
  src/configs/error-messages.js
Labels: Admin, bug

#914 fixed model form button responsive
  src/components/forms/model-form/model-form.styles.js
Labels: Admin, bug
