Repository ita-social-projects/horondi_admin, pull requests merged in 2021-05, with the labels that each got.

#723 component test
  src/pages/categories/category-delete/test/category-delete.test.js
  src/pages/categories/category-delete/test/store.js
Labels: Admin, test

#752 Enzyme test for navMenu
  src/components/nav-menu/tests/nav-menu.test.js
  src/components/nav-menu/tests/variables.js
Labels: Admin, test

#757 Fixed show comments issue
  src/components/comments-section/comments-section.js
  src/components/comments-section/comments-section.style.js
  src/components/forms/product-form/product-form.js
  src/components/forms/product-form/product-form.styles.js
  src/redux/comments/comments.operations.js
Labels: Admin, bug

#760 Added test for CreateColor component Test/428
  package-lock.json
  package.json
  src/components/create-color/tests/create-color.test.js
Labels: Admin, test

#763 when user is blocked log out and show error message
  src/error-messages/auth.js
  src/redux/auth/auth.operations.js
  src/redux/auth/auth.sagas.js
  src/redux/business-pages/business-pages.sagas.js
  src/redux/categories/categories.sagas.js
  src/redux/color/color.sagas.js
  src/redux/comments/comments.sagas.js
  src/redux/contact/contact.sagas.js
  src/redux/email-questions/email-questions.sagas.js
  src/redux/header/header.sagas.js
  src/redux/history/history.sagas.js
  src/redux/home-page-slides/home-page-slides.sagas.js
  src/redux/home/home.sagas.js
  src/redux/material/material.sagas.js
  src/redux/news/news.sagas.js
  src/redux/orders/orders.sagas.js
  src/redux/products/products.sagas.js
  src/redux/sizes/sizes.sagas.js
  src/redux/stats/stats.sagas.js
  src/redux/users/users.saga.js
  src/translations/user.translations.js
  src/utils/client.js
Labels: Admin, Task

#766 refactored photo upload
  src/components/forms/news-form/news-form.js
  src/configs/index.js
  src/configs/news-form-helpers.js
  src/utils/use-news-handlers.js
Labels: Admin, bug

#754 fixed initial values
  src/components/buttons/save-button/save-button.js
  src/components/forms/material-form/material-form.js
Labels: Admin, bug

#777 refactored test, removed magic strings, added a test case
  src/components/create-color/tests/create-color.test.js
  src/components/create-color/tests/mockStore.js
Labels: Admin, refactoring, test

#780 added column Size closes #740
  src/configs/table-head-row-titles.js
  src/pages/order-item/tabs/add-product-form/add-product-form.js
  src/pages/order-item/tabs/products.js
  src/utils/order.js
Labels: Admin

#790 fix problem with date
  src/pages/comments/comments.js
  src/pages/comments/tests/dataList.js
  src/pages/main-page/main-page.js
Labels: Admin, Hotfix

#767 Enzyme tests for Pattern page
  jest.config.js
  src/components/buttons/delete-button/__snapshots__/delete-button.test.js.snap
  src/components/buttons/save-button/__snapshots__/save-button.test.js.snap
  src/components/buttons/standard-button/__snapshots__/standard-button.test.js.snap
  src/components/checkbox-options/__snapshots__/checkbox-options.test.js.snap
  src/components/icons/customized-edit-icon/__snapshots__/edit-button.test.js.snap
  src/pages/pattern/pattern-page.js
  src/pages/pattern/tests/__snapshots__/pattern-page.test.js.snap
  src/pages/pattern/tests/mockStore.js
  src/pages/pattern/tests/pattern-page.test.js
Labels: Admin, test

#784 Fix adding contact on Admin #586
  package-lock.json
  src/components/buttons/save-button/save-button.js
  src/components/forms/contacts-form/contacts-form.js
  src/components/forms/language-panel/language-panel.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/utils/contacts-form.js
Labels: Admin, bug

#788 fix message in modal window
  src/components/colors-bar/colors-bar.js
  src/components/dialog-window/dialog-window.js
  src/configs/button-titles.js
  src/configs/messages.js
Labels: Admin, bug

#769 Enzyme tests for Material Form #447
  .gitignore
  jest.config.js
  src/components/forms/language-panel/language-panel.js
  src/components/forms/material-form/tests/material-form.test.js
  src/components/forms/material-form/tests/material-form.variables.js
Labels: Admin, test

#792 refactored link in home slides form
  src/configs/labels.js
Labels: Admin

#770 Test/500
  jest.config.js
  package-lock.json
  package.json
  src/components/forms/language-panel/language-panel.js
  src/configs/form-regexp.js
  src/pages/comments/comments.js
  src/pages/home-page/home-page.js
  src/pages/home-page/tests/home-page.test.js
  src/pages/login/tests/__snapshots__/login-page.test.js.snap
  src/pages/main-page/tests/main-page.test.js
  src/pages/main-page/tests/variables.js
  src/setupTests.js
  src/utils/contacts-form.js
Labels: Admin, test

#797 fix: make badge icon round
  src/components/filter-search-sort/filter-by-multiple-values/filter-by-multiple-values.styles.js
Labels: Hotfix

#762 product and category sections are highlighted
  src/components/forms/comment-form/tests/comment-form.test.js
  src/configs/routes.js
  src/pages/categories/categories.js
  src/pages/products/products-page.js
Labels: UI, fix
