Repository ita-social-projects/horondi_admin, pull requests merged in 2021-06, with the labels that each got.

#806 Fixed Data Range Picker
  package-lock.json
  package.json
  src/components/filter-search-sort/filter-by-date/filter-by-date.styles.js
  src/components/filter-search-sort/filter-by-date/nav-filter-by-date.js
  src/components/filter-search-sort/filter-navbar.js
  src/components/filter-search-sort/filter-navbar.styles.js
  src/consts/date-range-picker.js
  src/hooks/filters/use-comment-filters.js
  src/hooks/filters/use-history-filters.js
  src/hooks/filters/use-order-filters.js
Labels: Admin, fix

#755 Fixed bugs after changes in the DB (Feature/569)
  src/components/forms/pattern-form/pattern-form.js
  src/configs/table-head-row-titles.js
  src/pages/model/constructor/constructor-page/constructor-page.js
  src/pages/pattern/pattern-page.js
  src/pages/pattern/tests/__snapshots__/pattern-page.test.js.snap
  src/pages/pattern/tests/mockStore.js
  src/pages/pattern/tests/pattern-page.test.js
  src/redux/categories/categories.operations.js
  src/redux/constructor/constructor.operations.js
  src/redux/model/model.operations.js
  src/redux/model/model.sagas.js
  src/redux/pattern/pattern.actions.js
  src/redux/pattern/pattern.operations.js
  src/redux/pattern/pattern.reducer.js
  src/redux/pattern/pattern.sagas.js
  src/redux/pattern/pattern.types.js
  src/redux/pattern/tests/pattern.sagas.test.js
  src/redux/pattern/tests/pattern.variables.js
  src/utils/pattern-form.js
  src/utils/use-pattern-handlers.js
Labels: Admin, Database UI fix, bug

#812 Fixed routes / Fixed ModelForm Component after changes in DB
  .eslintrc
  package-lock.json
  src/components/forms/comment-form/tests/comment-form.test.js
  src/components/forms/model-form/model-form.js
  src/configs/routes.js
  src/pages/categories/categories.js
  src/pages/products/products-page.js
Labels: Admin, bug

#807 fixed behavior of back button on edit page after reload
  src/components/buttons/back-button/back-button.js
  src/components/forms/business-page-form/business-page-form.js
  src/components/forms/category-form/category-form.js
  src/components/forms/comment-form/comment-form.js
  src/components/forms/contacts-form/contacts-form.js
  src/components/forms/header-form/header-form.js
  src/components/forms/home-page-slide-form/home-page-slide-form.js
  src/components/forms/material-form/material-form.js
  src/components/forms/model-form/model-form.js
  src/components/forms/news-form/news-form.js
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/product-form/product-form.js
  src/components/forms/size-form/size-form.js
  src/configs/material-ui-constants.js
Labels: Admin, fix

#829 Fixed BackButton routes Hotfix/779
  src/components/forms/category-form/category-form.js
  src/pages/history/history-details/history-details.js
  src/pages/order-item/order-item.js
  src/pages/users/users-details/users-details.js
Labels: Admin, fix

#803 Enzyme test for category-form
  __mocks__/fileMock.js
  jest.config.js
  src/components/forms/category-form/tests/category-form.test.js
  src/components/forms/category-form/tests/category-form.variables.js
Labels: Admin, test

#826 Full refactor of QnA page with filters add-on bugFix/401
  src/components/filter-search-sort/filter-by-multiple-values/filter-by-multiple-values.styles.js
  src/components/filter-search-sort/filter-by-multiple-values/nav-filter-by-values.js
  src/configs/labels.js
  src/configs/material-ui-constants.js
  src/configs/table-head-row-titles.js
  src/containers/table-container-collapsable-row/index.js
  src/containers/table-container-collapsable-row/table-container-collapsable-row.js
  src/containers/table-container-collapsable-row/table-container-collapsable-row.styles.js
  src/containers/table-container-row/table-container-row.js
  src/containers/table-container-row/table-container-row.styles.js
  src/hooks/filters/use-questions-filter.js
  src/pages/email-questions/email-question-details/email-question-details.js
  src/pages/email-questions/email-question-details/email-question-details.styles.js
  src/pages/email-questions/email-question-details/index.js
  src/pages/email-questions/email-question-filter/email-question-filter.styles.js
  src/pages/email-questions/email-question-filter/email-questions-filter.js
  src/pages/email-questions/email-question-filter/index.js
  src/pages/email-questions/email-questions-list.js
  src/pages/email-questions/email-questions-list.styles.js
  src/pages/email-questions/tests/dataList.js
  src/pages/email-questions/tests/email-questions-list.test.js
  src/redux/email-questions/email-questions.actions.js
  src/redux/email-questions/email-questions.operations.js
  src/redux/email-questions/email-questions.reducer.js
  src/redux/email-questions/email-questions.sagas.js
  src/redux/email-questions/email-questions.types.js
  src/redux/selectors/email-questions.selectors.js
  src/routes/routes.js
  src/utils/email-question-list.js
  src/utils/questions.js
Labels: Admin, UI, bug, fix, refactoring
