Repository ita-social-projects/horondi_admin, pull requests merged in 2021-09, with the labels that each got.

#943 Create Basics Page and Forms
  src/components/forms/back-form/back-form.js
  src/components/forms/basics-form/basics-form.js
  src/components/forms/basics-form/basics-form.styles.js
  src/components/forms/basics-form/index.js
  src/components/forms/basics-form/tests/basics-form.test.js
  src/components/forms/basics-form/tests/basics-form.variables.js
  src/configs/button-titles.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/menu-categories.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/containers/back-materials-container/index.js
  src/containers/materials-container/index.js
  src/containers/materials-container/materials-container.js
  src/containers/materials-container/materials-container.styles.js
  src/hooks/filters/use-basic-filters.js
  src/pages/basics/basic-add/basic-add.js
  src/pages/basics/basic-add/basic-add.styles.js
  src/pages/basics/basic-add/index.js
  src/pages/basics/basic-details/basic-details.js
  src/pages/basics/basic-details/basic-details.styles.js
  src/pages/basics/basic-details/index.js
  src/pages/basics/basics-page.js
  src/pages/basics/index.js
  src/pages/basics/tests/basics-page.test.js
  src/pages/basics/tests/mockStore.js
  src/pages/model/constructor/constructor-page/constructor-page.js
  src/redux/back/back.operations.js
  src/redux/basics/basics.actions.js
  src/redux/basics/basics.operations.js
  src/redux/basics/basics.reducer.js
  src/redux/basics/basics.sagas.js
  src/redux/basics/basics.types.js
  src/redux/basics/tests/basics.actions.test.js
  src/redux/basics/tests/basics.reducer.test.js
  src/redux/basics/tests/basics.sagas.test.js
  src/redux/basics/tests/basics.variables.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/selectors/basics.selectors.js
  src/redux/table/table.reducer.js
  src/routes/routes.js
  src/translations/basics.translations.js
  src/utils/basics-form.js
  src/utils/use-basics-handlers.js
Labels: Admin, constructor

#949 Change add/edit additional price in Paterns, Closures, Materials, Sizes
  src/components/forms/closures-form/closures-form.js
  src/components/forms/closures-form/closures-form.styles.js
  src/components/forms/closures-form/tests/closures-form.test.js
  src/components/forms/material-form/material-form.js
  src/components/forms/material-form/material-form.styles.js
  src/components/forms/material-form/tests/material-form.variables.js
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/pattern-form/pattern-form.styles.js
  src/components/forms/size-form/size-form.js
  src/components/forms/size-form/tests/size-form.test.js
  src/configs/form-regexp.js
  src/configs/labels.js
  src/configs/titles.js
  src/pages/sizes/sizes.js
  src/redux/basics/basics.reducer.js
  src/redux/closures/closures.operations.js
  src/redux/currencies/currencies.actions.js
  src/redux/currencies/currencies.operations.js
  src/redux/currencies/currencies.reducer.js
  src/redux/currencies/currencies.saga.js
  src/redux/currencies/currencies.types.js
  src/redux/material/material.operations.js
  src/redux/model/model.actions.js
  src/redux/pattern/pattern.operations.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/sizes/sizes.operations.js
  src/utils/additionalPrice-helper.js
  src/utils/closures-form.js
  src/utils/material-form.js
  src/utils/pattern-form.js
  src/utils/size-helpers.js
  src/utils/use-closures-handlers.js
  src/utils/use-material-handlers.js
  src/utils/use-pattern-handlers.js
  src/validations/sizes/size-form-validation.js
Labels: Admin

#963 879/feature/create strap page
  src/components/forms/straps-form/index.js
  src/components/forms/straps-form/straps-form.js
  src/components/forms/straps-form/straps-form.styles.js
  src/components/forms/straps-form/tests/straps-form.test.js
  src/components/forms/straps-form/tests/straps.form.variables.js
  src/configs/button-titles.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/menu-categories.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/consts/history-actions.js
  src/hooks/filters/use-strap-filters.js
  src/hooks/filters/use-strap-filters.test.js
  src/pages/straps/index.js
  src/pages/straps/straps-add/index.js
  src/pages/straps/straps-add/straps-add.js
  src/pages/straps/straps-add/straps-add.styles.js
  src/pages/straps/straps-edit/index.js
  src/pages/straps/straps-edit/straps-edit.js
  src/pages/straps/straps-edit/straps-edit.styles.js
  src/pages/straps/straps-page.js
  src/pages/straps/tests/__snapshots__/straps.test.js.snap
  src/pages/straps/tests/straps.test.js
  src/pages/straps/tests/strapsList.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/selectors/straps.selectors.js
  src/redux/straps/straps.actions.js
  src/redux/straps/straps.operations.js
  src/redux/straps/straps.reducer.js
  src/redux/straps/straps.sagas.js
  src/redux/straps/straps.types.js
  src/redux/straps/tests/straps.actions.test.js
  src/redux/straps/tests/straps.reducer.test.js
  src/redux/straps/tests/straps.sagas.test.js
  src/redux/straps/tests/straps.variables.js
  src/routes/routes.js
  src/utils/straps-form.js
  src/utils/use-straps-handlers.js
  src/utils/use-straps-handlers.test.js
Labels: enhancement, Admin

#986 440/tests Writed tests for business-page-form
  src/components/forms/business-page-form/tests/__snapshots__/business-page-form.test.js.snap
  src/components/forms/business-page-form/tests/business-page-form.test.js
  src/components/forms/business-page-form/tests/business-page-form.variables.js
Labels: test, Admin

#984 983/tests Writed enzyme tests for header-form component
  src/components/forms/header-form/tests/header-form.test.js
  src/components/forms/header-form/tests/header-form.variables.js
Labels: test, Admin

#988 added disable if no content
  src/containers/product-materials-container/product-materials-container.js
  src/containers/product-species-container/product-species-container.js
Labels: Admin

#985 714/bugfix/add language validation for inputs
  src/components/colors-autocomplete/colors-autocomplete.js
  src/components/colors-bar/colors-bar.js
  src/components/editor/editor.js
  src/components/forms/business-page-form/business-page-form.js
  src/components/forms/closures-form/closures-form.js
  src/components/forms/header-form/header-form.js
  src/components/forms/home-page-slide-form/home-page-slide-form.js
  src/components/forms/language-panel/language-panel.js
  src/components/forms/material-form/material-form.js
  src/components/forms/model-form/model-form.js
  src/components/forms/news-form/news-form.js
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/size-form/size-form.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/containers/product-info-container/product-info-container.js
  src/hooks/product/use-product-validation.js
  src/translations/product.translations.js
  src/utils/size-helpers.js
  src/validations/models/model-form-validation.js
Labels: Admin

#987 validation reply comment
  src/components/forms/reply-comment-form/reply-comment-form.js
Labels: bug, Admin

#982 Refactored use-unsaved-changes-handler hook
  src/components/buttons/save-button/__snapshots__/save-button.test.js.snap
  src/components/buttons/save-button/save-button.js
  src/components/buttons/save-button/save-button.test.js
  src/components/forms/back-form/back-form.js
  src/components/forms/basics-form/basics-form.js
  src/components/forms/bottom-form/bottom-form.js
  src/components/forms/business-page-form/business-page-form.js
  src/components/forms/business-page-form/tests/__snapshots__/business-page-form.test.js.snap
  src/components/forms/category-form/category-form.js
  src/components/forms/closures-form/closures-form.js
  src/components/forms/comment-form/comment-form.js
  src/components/forms/constructor-form/constructor-form.js
  src/components/forms/contacts-form/contacts-form.js
  src/components/forms/header-form/header-form.js
  src/components/forms/home-page-slide-form/home-page-slide-form.js
  src/components/forms/material-form/material-form.js
  src/components/forms/model-form/model-form.js
  src/components/forms/news-form/news-form.js
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/pockets-form/pockets-form.js
  src/components/forms/position-form/position-form.js
  src/components/forms/product-form/product-form.js
  src/components/forms/reply-comment-form/reply-comment-form.js
  src/components/forms/size-form/size-form.js
  src/components/forms/straps-form/straps-form.js
  src/components/forms/tests/bottom/bottoms-form.test.js
  src/hooks/form-dialog/use-unsaved-changes-handler.js
  src/pages/comments/comment-edit/tests/__snapshots__/comment-edit.test.js.snap
Labels: refactoring, Admin

#1012 Fix Currency for Basic and Back On Admin #997
  src/components/forms/back-form/back-form.js
  src/components/forms/basics-form/basics-form.js
  src/components/forms/basics-form/basics-form.styles.js
  src/components/forms/basics-form/tests/basics-form.test.js
  src/components/forms/common.styles.js
  src/components/forms/tests/back/backs-form.test.js
  src/configs/labels.js
  src/configs/titles.js
  src/containers/additional-price-container/additional-price-container.js
  src/containers/additional-price-container/additional-price-container.styles.js
  src/containers/additional-price-container/index.js
  src/pages/back/back-page.js
  src/pages/basics/basics-page.js
  src/redux/back/back.operations.js
  src/redux/basics/basics.operations.js
  src/redux/root.saga.js
  src/utils/back-form.js
  src/utils/basics-form.js
  src/utils/use-back-handlers.js
  src/utils/use-basics-handlers.js
Labels: bug, Admin

#1011 add validation to business page and headers
  src/components/forms/business-page-form/business-page-form.js
  src/components/forms/header-form/header-form.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
Labels: Admin

#1014 Fixed create color on materials page
  src/components/create-color/create-color.js
  src/configs/error-messages.js
Labels: Admin

#947 Refactor filters for orders page, created main filter components
  src/components/container-filters/container-filters.js
  src/components/container-filters/container-filters.styles.js
  src/components/container-filters/index.js
  src/components/filters/clear/clear.js
  src/components/filters/clear/clear.styles.js
  src/components/filters/clear/index.js
  src/components/filters/date-range-picker/date-range-picker.js
  src/components/filters/date-range-picker/date-range-picker.styles.js
  src/components/filters/date-range-picker/index.js
  src/components/filters/option-picker/index.js
  src/components/filters/option-picker/option-picker.js
  src/components/filters/option-picker/option-picker.styles.js
  src/components/filters/options-picker/index.js
  src/components/filters/options-picker/options-picker.js
  src/components/filters/options-picker/options-picker.styles.js
  src/components/filters/search/index.js
  src/components/filters/search/search.js
  src/components/filters/search/search.styles.js
  src/components/filters/tests/filters.test.js
  src/components/nav-menu/nav-menu.js
  src/configs/button-titles.js
  src/configs/index.js
  src/pages/orders/components/filter-clear/filter-clear.js
  src/pages/orders/components/filter-clear/index.js
  src/pages/orders/components/filter-date-range-picker/filter-date-range-picker.js
  src/pages/orders/components/filter-date-range-picker/index.js
  src/pages/orders/components/filter-order-statuses-picker/filter-order-statuses-picker.js
  src/pages/orders/components/filter-order-statuses-picker/index.js
  src/pages/orders/components/filter-payment-statuses-picker/filter-payment-statuses-picker.js
  src/pages/orders/components/filter-payment-statuses-picker/index.js
  src/pages/orders/components/filter-search/filter-search.js
  src/pages/orders/components/filter-search/index.js
  src/pages/orders/components/filter-sort-picker/filter-sort-picker.js
  src/pages/orders/components/filter-sort-picker/index.js
  src/pages/orders/components/tests/orders-page.test.js
  src/pages/orders/orders-page.js
  src/utils/order.js
Labels: refactoring, Admin

#999 fixed none materials
  src/components/forms/product-form/product-form.js
  src/pages/products/product-add/products-add.js
Labels: bug, Admin

#967 966/features/disabled save button in edit forms
  src/components/forms/back-form/back-form.js
  src/components/forms/basics-form/basics-form.js
  src/components/forms/bottom-form/bottom-form.js
  src/components/forms/business-page-form/business-page-form.js
  src/components/forms/business-page-form/tests/__snapshots__/business-page-form.test.js.snap
  src/components/forms/business-page-form/tests/business-page-form.test.js
  src/components/forms/category-form/category-form.js
  src/components/forms/closures-form/closures-form.js
  src/components/forms/closures-form/tests/closures-form.test.js
  src/components/forms/comment-form/comment-form.js
  src/components/forms/constructor-form/constructor-form.js
  src/components/forms/contacts-form/contacts-form.js
  src/components/forms/contacts-form/tests/contacts-form.test.js
  src/components/forms/header-form/header-form.js
  src/components/forms/home-page-slide-form/home-page-slide-form.js
  src/components/forms/material-form/material-form.js
  src/components/forms/model-form/model-form.js
  src/components/forms/model-form/tests/model-form.test.js
  src/components/forms/news-form/news-form.js
  src/components/forms/news-form/tests/news-form.test.js
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/pockets-form/pockets-form.js
  src/components/forms/pockets-form/tests/pockets-form.test.js
  src/components/forms/position-form/position-form.js
  src/components/forms/product-form/product-form.js
  src/components/forms/reply-comment-form/reply-comment-form.js
  src/components/forms/size-form/size-form.js
  src/components/forms/straps-form/straps-form.js
  src/hooks/forms/use-changed-values-checker.js
  src/hooks/forms/use-changed-values-checker.test.js
  src/pages/comments/comment-edit/tests/__snapshots__/comment-edit.test.js.snap
Labels: Admin, functional

#1015 fixed orders error
  src/pages/model/constructor/constructor-page/constructor-page.js
  src/pages/order-item/tabs/add-product-form/add-product-form.js
  src/pages/order-item/tabs/edit-product-form/edit-product-form.js
  src/pages/order-item/tabs/products.js
  src/redux/orders/orders.operations.js
  src/utils/order.js
Labels: bug, Admin

#1023 431/tests Enzyme tests for DialogWindow component
  src/components/dialog-window/tests/__snapshots__/dialog-window.test.js.snap
  src/components/dialog-window/tests/dialog-window.test.js
  src/components/dialog-window/tests/dialog-window.variables.js
Labels: test, Admin

#1013 Hint buttons
  src/components/forms/business-page-form/tests/__snapshots__/business-page-form.test.js.snap
  src/components/forms/size-form/size-form.js
  src/components/forms/size-form/size-form.styles.js
  src/components/tooltip/index.js
  src/components/tooltip/tests/tooltip.test.js
  src/components/tooltip/tests/variables.js
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.styles.js
  src/configs/tooltip-titles.js
Labels: Admin

#1016 424/tests Tests for ColorCircle
  src/components/color-circle/tests/color-circle.test.js
Labels: test, Admin

#1030 968/refactor/filters sizes and materials
  src/components/container-filters/tests/container-filters.test.js
  src/components/filters-components/filter-clear/component-filter-clear.js
  src/components/filters-components/filter-clear/index.js
  src/components/filters-components/filter-date-range-picker/component-filter-date-range-picker.js
  src/components/filters-components/filter-date-range-picker/index.js
  src/components/filters-components/filter-multiple-picker/component-filter-multiple-picker.js
  src/components/filters-components/filter-multiple-picker/index.js
  src/components/filters-components/filter-radio-picker/component-filter-radio-picker.js
  src/components/filters-components/filter-radio-picker/index.js
  src/components/filters-components/filter-search/component-filter-search.js
  src/components/filters-components/filter-search/index.js
  src/components/filters-components/filter-single-picker/component-filter-single-picker.js
  src/components/filters-components/filter-single-picker/index.js
  src/components/filters-components/tests/filters-components.test.js
  src/pages/material/filters/filters.js
  src/pages/material/material-page.js
  src/pages/orders/components/tests/filters.test.js
  src/pages/orders/filters/filters.js
  src/pages/orders/orders-page.js
  src/pages/sizes/filters/filters.js
  src/pages/sizes/sizes.js
  src/pages/sizes/tests/sizes.test.js
  src/utils/material.js
  src/utils/size-helpers.js
Labels: Admin

#1048 bugFix/1027 Edited label no orders
  src/configs/messages.js
Labels: refactoring, Admin

#1047 512/tests Writed enzyme tests for news page
  src/pages/news/tests/__snapshots__/news.test.js.snap
  src/pages/news/tests/news-page.test.js
  src/pages/news/tests/newsList.js
Labels: test, Admin

#1045 tests/379/ Added e2e tests for headers page
  cypress/integration/headers-page/headers-page.test.js
  cypress/integration/headers-page/headers-page.variables.js
  cypress/support/commands.js
Labels: Admin, e2e test

#1022 Bug fix/979/change photo load
  src/components/filters/options-picker/options-picker.js
  src/components/forms/home-page-slide-form/home-page-slide-form.js
  src/configs/home-page-slide-helpers.js
  src/configs/index.js
  src/utils/use-home-page-slide-handlers.js
Labels: Admin

#1053 fixed phone number
  src/utils/format-phone-number.js
Labels: bug, Admin

#1054 Add new field, registered user, in order list
  src/configs/table-head-row-titles.js
  src/pages/news/tests/__snapshots__/news-page.test.js.snap
  src/pages/orders/orders-page.js
Labels: Admin, functional

#1071 Spread out buttons in confirmation modal
  src/components/dialog-window/dialog-window.js
  src/components/dialog-window/dialog-window.styles.js
Labels: bug, Admin

#1049 1040/refactor/filters category models
  src/configs/button-titles.js
  src/pages/categories/categories.js
  src/pages/categories/filters/filters.js
  src/pages/categories/tests/categories.test.js
  src/pages/categories/tests/filters.test.js
  src/pages/categories/tests/variables.js
  src/pages/model/filters/filters.js
  src/pages/model/model-page.js
  src/pages/model/tests/filters.test.js
  src/utils/model.js
Labels: Admin

#1056 add user form
  src/components/forms/user-form/index.js
  src/components/forms/user-form/tests/user-form.test.js
  src/components/forms/user-form/tests/user.form.variables.js
  src/components/forms/user-form/user-form.js
  src/components/forms/user-form/user-form.styles.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/routes.js
  src/hooks/user/use-users-handlers.js
  src/pages/users/user/user-details/index.js
  src/pages/users/user/user-details/user-details.js
  src/pages/users/user/user-details/user-details.styles.js
  src/pages/users/users-details/containers/user-details-card/user-details-card.js
  src/pages/users/users-details/users-details.js
  src/redux/users/users.actions.js
  src/redux/users/users.operations.js
  src/redux/users/users.saga.js
  src/redux/users/users.types.js
  src/routes/routes.js
  src/utils/use-user-handlers.js
  src/utils/user-form.js
Labels: Admin
