Repository ita-social-projects/horondi_admin, pull requests merged in 2021-04, with the labels that each got.

#690 add block user functionality
  src/configs/error-messages.js
  src/configs/statuses.js
  src/consts/user-block-status.js
  src/pages/users/components/admin-tab/admin-tab.js
  src/pages/users/components/user-tab/user-tab.js
  src/pages/users/users-details/containers/user-details-card/user-details-card.js
  src/pages/users/users-details/containers/user-details-card/user-details-card.styles.js
  src/pages/users/users-details/users-details.js
  src/redux/users/tests/users.actions.test.js
  src/redux/users/tests/users.reducer.test.js
  src/redux/users/tests/users.saga.test.js
  src/redux/users/users.actions.js
  src/redux/users/users.operations.js
  src/redux/users/users.reducer.js
  src/redux/users/users.saga.js
  src/redux/users/users.types.js
  src/utils/client.js
  src/utils/user.js
Labels: Admin, Task

#689 Fixed a small bug on the Home Page related to updating images #682
  src/redux/home/home.reducer.js
  src/redux/home/home.sagas.js
  src/redux/home/tests/home.reducer.test.js
  src/redux/home/tests/home.sagas.test.js
  src/redux/home/tests/home.variables.js
Labels: Admin, bug

#687 fixed date view
  src/pages/main-page/main-page.js
  src/pages/orders/orders-page.js
Labels: Admin

#678 Fixed test for comments
  src/redux/comments/tests/comments.actions.test.js
  src/redux/comments/tests/comments.sagas.test.js
  src/redux/contact/tests/contact.sagas.test.js
  src/redux/material/tests/material.saga.test.js
  src/redux/material/tests/material.variables.js
  src/redux/model/tests/model.saga.test.js
Labels: test

#695 refactored pagination
  src/pages/email-questions/email-questions-list.js
Labels: Admin

#703 Feature/612
  src/configs/button-titles.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/configs/index.js
  src/configs/material-ui-constants.js
  src/configs/statuses.js
  src/hooks/user/use-users-handlers.js
  src/pages/users/confirm-user/confirm-user.js
  src/pages/users/confirm-user/confirm-user.styles.js
  src/pages/users/register-user/register-user.js
  src/pages/users/register-user/register-user.styles.js
  src/pages/users/users-details/containers/user-details-card/user-details-card.js
  src/pages/users/users-details/users-details.js
  src/pages/users/users-page.js
  src/redux/auth/auth.sagas.js
  src/redux/selectors/users.selectors.js
  src/redux/users/tests/users.saga.test.js
  src/redux/users/tests/users.variables.js
  src/redux/users/users.actions.js
  src/redux/users/users.operations.js
  src/redux/users/users.reducer.js
  src/redux/users/users.saga.js
  src/redux/users/users.types.js
Labels: Admin

#718 Fixed appearing error message
  src/redux/business-pages/business-pages.operations.js
  src/redux/comments/comments.operations.js
  src/redux/contact/contact.operations.js
  src/redux/header/header.operations.js
  src/redux/home-page-slides/home-page-slides.operations.js
  src/redux/home/home.operations.js
  src/redux/material/material.operations.js
  src/redux/sizes/sizes.operations.js
Labels: Admin, bug

#720 Fixed regEx for Quill WYSIWYG editor field #704
  src/configs/form-regexp.js
Labels: Admin, bug

#721 Save button is active when main fields are filled
  src/components/forms/language-panel/language-panel.js
  src/components/forms/news-form/news-form.js
Labels: Admin, bug

#717 Implement history pages on admin part
  package-lock.json
  src/components/filter-search-sort/nav-clear-filters/nav-clear-filters.js
  src/components/filter-search-sort/nav-search/nav-search.js
  src/configs/button-titles.js
  src/configs/labels.js
  src/configs/material-ui-constants.js
  src/configs/menu-categories.js
  src/configs/messages.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/consts/history-actions.js
  src/hooks/filters/use-history-filters.js
  src/pages/history/history-details/history-details.js
  src/pages/history/history-details/history-details.styles.js
  src/pages/history/history-details/index.js
  src/pages/history/history-filters/filter-by-date/filter-by-date.js
  src/pages/history/history-filters/filter-by-date/filter-by-date.styles.js
  src/pages/history/history-filters/filter-by-date/index.js
  src/pages/history/history-filters/filter-by-miltiple-values/filter-by-multiple-values.styles.js
  src/pages/history/history-filters/filter-by-miltiple-values/filter-by-values.js
  src/pages/history/history-filters/filter-by-miltiple-values/index.js
  src/pages/history/history-filters/history-filters.js
  src/pages/history/history-filters/history-filters.styles.js
  src/pages/history/history-filters/index.js
  src/pages/history/history.js
  src/pages/history/history.styles.js
  src/pages/history/index.js
  src/pages/sizes/sizes.js
  src/redux/history/history.actions.js
  src/redux/history/history.operations.js
  src/redux/history/history.reducer.js
  src/redux/history/history.sagas.js
  src/redux/history/history.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/selectors/history.js
  src/routes/routes.js
  src/utils/history.js
Labels: Admin, Task

#737 Deleted recent changes and left recent orders and recent comments o…
  src/pages/main-page/main-page.js
  src/pages/main-page/main-page.styles.js
Labels: Admin

#727 Test/426
  src/components/colors-bar/colors-bar.js
  src/components/colors-bar/colors-bar.styles.js
  src/components/colors-bar/tests/colors-bar.test.js
  src/components/colors-bar/tests/mockStore.js
Labels: test
