Repository ita-social-projects/horondi_admin, pull requests merged in 2022-02, with the labels that each got.

#1208 add universal sorting for admin pages
  src/components/filter-search-sort/nav-sort/nav-sort.js
  src/components/filters-components/filter-multiple-picker/component-filter-multiple-picker.js
  src/components/filters/option-picker/option-picker.js
  src/hooks/filter/useFilterSearchAndSort.js
  src/pages/material/material-page.js
  src/pages/model/filters/filters.js
Labels: Admin, feature

#1207 Feature/1196/create table about us
  src/configs/table-head-row-titles.js
  src/containers/table-container-row/table-container-row.js
  src/containers/table-container-row/table-container-row.styles.js
  src/index.js
  src/pages/about-us/about-us.js
  src/pages/about-us/operations/mockdata.js
  src/pages/about-us/tests/about-us.spec.js
Labels: Admin, feature

#1212 Feature/1196/create table about us
  src/configs/table-head-row-titles.js
  src/containers/table-container-row/table-container-row.js
  src/containers/table-container-row/table-container-row.styles.js
  src/pages/about-us/tests/about-us.spec.js
Labels: bug

#1218 Feature/1187/create custom hook for searching and filtering
  src/components/filter-search-sort/filter-by-multiple-values/nav-filter-by-values.js
  src/components/filter-search-sort/nav-search/nav-search.js
  src/components/filters/date-range-picker/date-range-picker.js
  src/components/filters/option-picker/option-picker.js
  src/components/filters/options-picker/options-picker.js
  src/components/filters/search/search.js
  src/hooks/filter/useFilterSearchAndSort.js
  src/utils/history.js
Labels: Admin, feature

#1209 Admin: generate certificates button invokes mutation
  src/configs/titles.js
  src/pages/certificates/certificatesTable/certificateTable.js
  src/pages/certificates/create-certificate/create-certificate.js
  src/pages/certificates/operations/certificate.mutation.js
  src/pages/certificates/tests/create-certificate.spec.js
  src/pages/certificates/tests/create-certificate.variables.js
Labels: Admin

#1214 Cherry pick commit
  src/components/nav-menu/nav-menu.js
  src/configs/index.js
  src/configs/menu-categories.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/consts/menu-categories.js
  src/pages/material/material-about.js
  src/pages/material/operations/materials-page.mutations.js
  src/pages/material/operations/materials-page.queries.js
  src/pages/material/tests/material-about.spec.js
  src/pages/material/tests/material-about.variables.js
  src/routes/routes.js
Labels: Admin, functional

#1213 Feature/1206/replace-dispatch-snackBar
  src/components/forms/category-form/category-form.js
  src/components/forms/contacts-form/contacts-form.js
  src/components/forms/model-form/model-form.js
  src/components/forms/pockets-form/pockets-form.js
  src/pages/promo-code/promo-code-add/promo-code-add.js
  src/pages/promo-code/promo-code-edit/promo-code-edit.js
Labels: refactoring, Admin

#1217 Feature/1188/add categories to promo code
  src/configs/orders.js
  src/pages/promo-code/promo-code-form/promo-code-form.js
  src/pages/promo-code/promo-code-form/promo-code-form.style.js
  src/pages/promo-code/promo-code-form/test/promo-code-form.spec.js
  src/pages/promo-code/promo-code-page.js
  src/validations/promo-code/promo-code-validation.js
Labels: Admin, feature

#1225 Check and fix all code smells
  src/configs/form-regexp.js
  src/pages/home-page/tests/home-page.test.js
  src/pages/orders/filters/filters.js
Labels: Admin, Sonar
