Repository ita-social-projects/horondi_admin, pull requests merged in 2022-07, with the labels that each got.

#1406 Improvement/1402/document title according to current page
  src/components/app-wrapper/app-wrapper.js
  src/components/app-wrapper/index.js
  src/components/app/app.js
  src/configs/index.js
  src/configs/menu-categories.js
  src/hooks/doc-title-update/useDocTitleUpdate.js
  src/hooks/doc-title-update/useDocTitleUpdate.spec.js
  src/index.js
Labels: Admin

#1400 added goBack onClick event on goback button
  src/containers/table-container-row/table-container-row.js
  src/pages/model/constructor/constructor-page/constructor-page.js
  src/pages/model/tests/constructor-page.test.js
Labels: good first issue, refactoring

#1414 Add a favicon for Admin's page
  public/favicon.ico
  public/favicon.svg
  public/index.html
Labels: Admin

#1410 [Orders] Displayed price without discount within promo code was used
  src/configs/table-head-row-titles.js
  src/pages/order-item/order-item.js
  src/pages/order-item/tabs/add-product-form/add-product-form.js
  src/pages/order-item/tabs/edit-product-form/edit-product-form.js
  src/pages/order-item/tabs/products.js
  src/pages/order-item/tabs/tests/add-product-form-tests/add-product-form.spec.js
  src/pages/order-item/tabs/tests/add-product-form-tests/add-product-form.variables.js
  src/pages/order-item/tabs/tests/edit-product-form-tests/edit-product-form.spec.js
  src/pages/order-item/tabs/tests/edit-product-form-tests/edit-product-form.variables.js
  src/pages/order-item/tabs/tests/products-tests/products.spec.js
  src/pages/order-item/tabs/tests/products-tests/products.variables.js
  src/redux/orders/orders.operations.js
  src/utils/order.js
  src/utils/tests/order.test.js
  src/utils/tests/order.variables.js
Labels: test, Admin

#1415 Created page for adding about-materials section
  src/components/forms/material-about-form/index.js
  src/components/forms/material-about-form/material-about-add-form.js
  src/components/forms/material-about-form/material-about-add-form.styles.js
  src/components/forms/material-about-form/tests/material-about-add-form.spec.js
  src/components/forms/material-about-form/tests/material-about-add-form.variables.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/configs/routes.js
  src/pages/material/material-about-add.js
  src/pages/material/material-about.js
  src/pages/material/operations/materials-page.mutations.js
  src/pages/material/operations/materials-page.queries.js
  src/pages/material/tests/material-about-add.spec.js
  src/routes/routes.js
  src/utils/material-about.js
  src/validations/material-about/material-about-validation.js
Labels: Admin, feature

#1424 Add the possibility to edit items in the About materials tab
  src/components/forms/material-about-form/index.js
  src/components/forms/material-about-form/material-about-form.js
  src/components/forms/material-about-form/material-about-form.styles.js
  src/components/forms/material-about-form/tests/material-about-form.spec.js
  src/components/forms/material-about-form/tests/material-about-form.variables.js
  src/configs/routes.js
  src/pages/material/material-about-details.js
  src/pages/material/material-about.js
  src/pages/material/operations/materials-page.mutations.js
  src/pages/material/operations/materials-page.queries.js
  src/pages/material/tests/material-about-details.spec.js
  src/pages/material/tests/material-about.spec.js
  src/pages/material/tests/material-about.variables.js
  src/routes/routes.js
  src/utils/material-about.js
Labels: Admin

#1420 Improvement/1413/move size form to model form
  src/components/buttons/save-button/save-button.js
  src/components/forms/constructor-form/constructor-model-form.js
  src/components/forms/model-form/model-form.js
  src/components/forms/model-form/tests/model-form.spec.js
  src/components/forms/product-form/product-form.js
  src/components/forms/size-form/size-form-accordion/index.js
  src/components/forms/size-form/size-form-accordion/size-form-accordion.js
  src/components/forms/size-form/size-form-accordion/tests/size-form-accordion.spec.js
  src/components/forms/size-form/size-form.js
  src/components/forms/size-form/size-form.styles.js
  src/components/forms/size-form/tests/size-form.spec.js
  src/configs/error-messages.js
  src/configs/menu-categories.js
  src/configs/routes.js
  src/hooks/filters/useSizesFilters.js
  src/hooks/model-form/use-size-handlers.js
  src/hooks/model-form/use-size-handlers.spec.js
  src/hooks/model-form/use-size-handlers.variables.js
  src/pages/products/product-edit/product-edit.js
  src/pages/products/tests/product-page.spec.js
  src/pages/sizes/filters/filters.js
  src/pages/sizes/index.js
  src/pages/sizes/sizes-add/index.js
  src/pages/sizes/sizes-add/size-add.js
  src/pages/sizes/sizes-add/size-add.styles.js
  src/pages/sizes/sizes-edit/index.js
  src/pages/sizes/sizes-edit/size-edit.js
  src/pages/sizes/sizes-edit/size-edit.styles.js
  src/pages/sizes/sizes.js
  src/pages/sizes/sizes.styles.js
  src/pages/sizes/tests/mockStoreReturner.js
  src/pages/sizes/tests/sizes.test.js
  src/redux/model/model.operations.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/selectors/sizes.selector.js
  src/redux/sizes/sizes.actions.js
  src/redux/sizes/sizes.operations.js
  src/redux/sizes/sizes.reducer.js
  src/redux/sizes/sizes.sagas.js
  src/redux/sizes/sizes.types.js
  src/redux/sizes/tests/sizes.actions.test.js
  src/redux/sizes/tests/sizes.reducer.test.js
  src/redux/sizes/tests/sizes.sagas.test.js
  src/redux/sizes/tests/sizes.variables.js
  src/routes/routes.js
  src/utils/model-form.js
  src/utils/size-helpers.js
  src/validations/models/model-form-validation.js
  src/validations/sizes/size-form-validation.js
Labels: Admin
