Repository ita-social-projects/horondi_admin, pull requests merged in 2022-11, with the labels that each got.

#1493 fix table header in email questions table
  src/containers/table-container-collapsable-row/table-container-collapsable-row.js
Labels: bug, Admin

#1494 Bugfix/1490/1491/fix 'coments' and 'user information' tables
  src/pages/comments/comments.js
  src/pages/users/components/user-tab/user-tab.js
Labels: bug, Admin

#1497 added inProgress to filter and show certificates with inProgress status
  src/consts/certificate-status.js
  src/pages/certificates/certificates-page.js
  src/pages/certificates/hooks/use-certificates.js
  src/pages/certificates/operations/certificate.queries.js
  src/pages/certificates/tests/certificates-page.variables.js
  src/pages/certificates/tests/use-certificates.spec.js
Labels: Admin

#1500 refactored constructor
  src/components/autocomplete-options/autocomplete-options.js
  src/pages/constructor-list/constructor-list-page.js
  src/pages/constructor-list/tests/mockStore.js
Labels: Admin, constructor

#1499 Bug/1489/fix date to and code validations
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/pages/promo-code/promo-code-form/promo-code-form.js
Labels: bug, Admin

#1487 button is disabled when payment method is card
  src/pages/order-item/tabs/general.js
Labels: bug, Admin

#1498 changed certificate images
  src/assets/images/certificate.png
  src/configs/certificate.js
  src/configs/index.js
  src/pages/certificates/certificate/certificate.js
  src/pages/certificates/certificate/certificate.styles.js
  src/pages/certificates/certificates-page.js
  src/pages/certificates/img/certificate.svg
Labels: bug, Admin

#1503 bugfix/1423/fix delete pop-up
  src/hooks/deleteValidation/useDeleteValidation.js
  src/pages/products/products-page.js
  src/utils/use-success-snackbar.js
Labels: bug, Admin

#1507 Bug/1506/fix main material and main material color fields
  src/components/forms/product-form/product-form.js
  src/utils/product-form.js
Labels: bug, Admin

#1505 Added list shows discount information
  src/components/nav-bar/nav-bar.styles.js
  src/configs/orders.js
  src/consts/menu-categories.js
  src/containers/table-container-row/table-container-row.js
  src/pages/about-us/about-us.js
  src/pages/certificates/operations/certificate.queries.js
  src/pages/order-item/order-item.js
  src/pages/order-item/tabs/add-product-form/add-product-form.js
  src/pages/order-item/tabs/add-product-form/add-product-form.styles.js
  src/pages/order-item/tabs/products.js
  src/redux/orders/orders.operations.js
  src/utils/order.js
  src/utils/order.values.js
Labels: bug, Admin

#1508 fixed constructor bugs
  src/components/forms/constructor-form/constructor-list-accordion/constructor-list-accordion.js
  src/components/forms/constructor-form/constructor-list-accordion/constructor-list-accordion.styles.js
  src/components/forms/constructor-form/constructor-list-base-price/constructor-list-base-price.js
  src/components/forms/constructor-form/constructor-list-base-price/constructor-list-base-price.styles.js
  src/components/forms/constructor-form/constructor-model-form.js
  src/configs/error-messages.js
  src/configs/index.js
  src/configs/labels.js
  src/containers/constructor-form-container/constructor-form-container.js
  src/pages/constructor-list/constructor-edit/constructor-edit.js
  src/pages/constructor-list/tests/constructor-details.spec.js
  src/pages/constructor-list/tests/constructor-edit.spec.js
  src/pages/constructor-list/tests/constructor-list-page.spec.js
  src/pages/constructor-list/tests/mockStore.js
  src/utils/constructor-model-form.js
  src/utils/constructorItemPrice.js
  src/utils/use-constructor-handlers.js
  src/validations/constructor/constructor-form-container.js
Labels: Admin, constructor

#1513 fix useMemo forms
  src/components/forms/business-page-form/business-page-form.js
  src/components/forms/business-page-form/tests/business-page-form.test.js
  src/components/forms/business-page-form/tests/business-page-form.variables.js
  src/components/forms/questions-answers-form/questions-answers-form.js
  src/configs/titles.js
  src/utils/business-page-form.js
  src/utils/questions-answers-form.js
  src/utils/questions-answers-form.test.js
  src/utils/use-business-handlers.js
  src/utils/use-questions-answers-handlers.js
  src/utils/use-questions-answers.test.js
Labels: bug, Admin

#1516 Bugfix/1457/categoris form react on image change
  src/components/forms/business-page-form/business-page-form.js
  src/components/forms/category-form/category-form.js
  src/components/forms/questions-answers-form/questions-answers-form.js
  src/utils/use-questions-answers-handlers.js
Labels: bug, Admin

#1514 added possibility to use certificate for order
  src/configs/button-titles.js
  src/configs/orders.js
  src/pages/certificates/operations/certificate.queries.js
  src/pages/order-item/tabs/add-product-form/add-product-form.js
  src/pages/order-item/tabs/add-product-form/add-product-form.styles.js
  src/pages/order-item/tabs/products.js
  src/pages/order-item/tabs/tests/add-product-form-tests/add-product-form.spec.js
  src/pages/order-item/tabs/tests/add-product-form-tests/add-product-form.variables.js
  src/utils/order.js
Labels: Admin

#1525 Email-question page changed after answering to the question
  src/redux/email-questions/email-questions.sagas.js
Labels: bug, Admin

#1529 filters list of not available constructors
  src/pages/constructor-list/constructor-list-page.js
Labels: bug, Admin, constructor

#1523 Bug/1517/fix promocode discount
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/configs/orders.js
  src/pages/promo-code/promo-code-form/test/promo-code-form.spec.js
  src/pages/promo-code/promo-code-page.js
  src/validations/promo-code/promo-code-validation.js
Labels: bug, Admin

#1522 [Admin] Show the total price of a product in the product folder
  src/components/buttons/back-button/back-button.js
  src/components/comments-section/comments-section.js
  src/components/filter-search-sort/filter-by-date/nav-filter-by-date.js
  src/components/filters-components/filter-date-range-picker/component-filter-date-range-picker.js
  src/components/filters/date-range-picker/date-range-picker.js
  src/components/forms/language-panel/language-panel.js
  src/components/forms/product-form/product-form.js
  src/configs/table-head-row-titles.js
  src/containers/images-preview-container/images-preview-container.js
  src/containers/product-info-container/product-info-container.js
  src/containers/product-materials-container/product-materials-container.js
  src/containers/product-materials-container/tests/product-info-container.spec.js
  src/containers/product-species-container/product-species-container.js
  src/containers/product-species-container/tests/product-species-container.spec.js
  src/pages/history/history-details/history-details.js
  src/pages/products/products-page.js
  src/propTypes/product-containers.js
  src/redux/products/products.operations.js
Labels: Admin
