Repository ita-social-projects/horondi_admin, pull requests merged in 2022-01, with the labels that each got.

#1144 Refactor/1133/date range picker
  src/components/filters-components/filter-date-range-picker/component-filter-date-range-picker.js
  src/components/filters-components/filter-multiple-picker/component-filter-multiple-picker.js
  src/components/filters/date-range-picker/date-range-picker.js
  src/components/filters/date-range-picker/date-range-picker.styles.js
  src/pages/orders/filters/filters.js
  src/redux/orders/orders.reducer.js
  src/redux/orders/test/orders.variables.js
  src/utils/order.js
Labels: refactoring, Admin

#1160 Add certificates under catalogue
  package-lock.json
  package.json
  src/components/nav-menu/nav-menu.js
  src/components/nav-menu/tests/nav-menu.spec.js
  src/configs/index.js
  src/configs/menu-categories.js
  src/configs/routes.js
  src/consts/menu-categories.js
Labels: Admin, functional

#1161 fix navbar on admin
  src/components/nav-menu/nav-menu.js
Labels: bug, Admin, functional

#1170 Test/1152/home page
  .env.example
  package.json
  src/pages/home-page/test/home-page.spec.js
Labels: Admin

#1173 feature/1159/create-certificate
  src/configs/button-titles.js
  src/configs/titles.js
  src/pages/certificates/certificatesTable/certificateTable.js
  src/pages/certificates/certificatesTable/index.js
  src/pages/certificates/checkBoxes/checkBoxes.js
  src/pages/certificates/checkBoxes/checkboxes.styles.js
  src/pages/certificates/checkBoxes/index.js
  src/pages/certificates/create-certificate/create-certificate.js
  src/pages/certificates/create-certificate/create-certificate.styles.js
  src/pages/certificates/create-certificate/index.js
  src/pages/certificates/tests/create-certificate.spec.js
  src/routes/routes.js
Labels: Admin

#1194 Feature/1190/add about us route
  src/components/nav-menu/tests/nav-menu.spec.js
  src/configs/button-titles.js
  src/configs/menu-categories.js
  src/configs/routes.js
  src/configs/titles.js
  src/pages/about-us/about-us-add/about-us-add.js
  src/pages/about-us/about-us-add/about-us-add.styles.js
  src/pages/about-us/about-us-add/index.js
  src/pages/about-us/about-us.js
  src/pages/about-us/about-us.styles.js
  src/pages/about-us/index.js
  src/routes/routes.js
Labels: Admin

#1195 Feature/1191/add about materials page
  src/components/forms/news-form/news-form.styles.js
  src/components/nav-menu/tests/nav-menu.spec.js
  src/configs/button-titles.js
  src/configs/menu-categories.js
  src/configs/routes.js
  src/pages/material/material-about-add.js
  src/pages/material/material-about.js
  src/pages/material/tests/material-about-add.spec.js
  src/pages/material/tests/material-about.spec.js
  src/routes/routes.js
Labels: Admin

#1171 Feature/957/promocodes
  package-lock.json
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/components/app/app-theme/typography.styles.js
  src/components/nav-bar/icons.js
  src/components/nav-menu/nav-menu.js
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/configs/index.js
  src/configs/menu-categories.js
  src/configs/orders.js
  src/configs/product-translations.js
  src/configs/routes.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/consts/menu-categories.js
  src/containers/table-container-head/table-container-head.styles.js
  src/index.css
  src/index.js
  src/pages/promo-code/operations/promo-code.mutation.js
  src/pages/promo-code/operations/promo-code.queries.js
  src/pages/promo-code/promo-code-add/promo-code-add.js
  src/pages/promo-code/promo-code-add/promo-code-add.styles.js
  src/pages/promo-code/promo-code-add/tests/promo-code-add.spec.js
  src/pages/promo-code/promo-code-page.js
  src/pages/promo-code/promo-code-page.styles.js
  src/pages/promo-code/tests/promo-code-page.spec.js
  src/pages/promo-code/tests/promo-code-page.variables.js
  src/routes/routes.js
  src/validations/promo-code/promo-code-validation.js
Labels: test, Admin

#1199 increasing the number of patterns
  src/components/forms/constructor-form/constructor-list-accordion/constructor-list-accordion.js
Labels: Admin

#1145 Tests/421/refactoring tests
  src/components/buttons/standard-button/standard-button.test.js
Labels: test, Admin

#1200 Feature/1197/add table on about material page
  src/configs/table-head-row-titles.js
  src/index.js
  src/pages/material/material-about.js
  src/pages/material/material-page.styles.js
  src/pages/material/tests/material-about.spec.js
Labels: Admin

#1201 refactor/1185/refactor promo code add
  src/pages/promo-code/promo-code-add/promo-code-add.js
  src/pages/promo-code/promo-code-add/tests/promo-code-add.spec.js
  src/pages/promo-code/promo-code-form/promo-code-form.js
  src/pages/promo-code/promo-code-form/promo-code-form.style.js
Labels: refactoring, Admin

#1174 Add validation
  src/components/app/app.js
  src/components/dialog-window/dialog-window.js
  src/fragmentTypes.json
  src/hooks/deleteValidation/useDeleteValidation.js
  src/pages/material/material-page.js
  src/pages/products/products-page.js
  src/redux/products/products.operations.js
  src/redux/products/products.sagas.js
  src/redux/products/tests/products.saga.test.js
  src/routes/routes.js
  src/utils/use-success-snackbar.js
Labels: Admin
