Repository ita-social-projects/horondi_admin, pull requests merged in 2022-06, with the labels that each got.

#1356 [Order] Incorrect sorting by order price.
  src/configs/filter-labels.js
Labels: Admin

#1357 removed unnecessary descriptions validation
  src/components/forms/home-page-slide-form/home-page-slide-form.js
  src/configs/error-messages.js
  src/configs/index.js
Labels: Admin, fix, Database UI fix, redesign

#1368 Fixed navbar collapsing
  src/components/icons/customized-edit-icon/customized-edit-icon.js
  src/components/nav-menu/nav-menu.js
  src/containers/table-container-row/table-container-row.js
  src/pages/about-us/tests/about-us.spec.js
  src/pages/promo-code/tests/promo-code-page.spec.js
Labels: bug, Admin

#1366 Products/1359/no possibility to save changes after editing the product
  src/components/forms/product-form/product-form.js
Labels: bug, Admin

#1367 Fixed bug with changing or adding order status
  src/utils/handle-orders-page.js
Labels: bug, Admin

#1370 bugfix/1360/error_after_clicking_the_save_button_switched_to_another_page-questions-answers_list
  src/redux/business-pages/business-pages.sagas.js
Labels: bug, Admin

#1372 Text "Гаманець ...." in sorting gets out of the block
  src/components/filter-search-sort/filter-by-multiple-values/filter-by-multiple-values.styles.js
Labels: Admin

#1373 When sorting for answers data, there are fileds with no answers
  src/configs/filter-labels.js
Labels: Admin

#1382 Certificate/1375/incorrect modal text when clicking on editing btn
  src/configs/titles.js
Labels: bug, Admin

#1386 correct ukr post submit
  src/utils/order.js
Labels: bug, Admin

#1383 Promocodes/1376/fixed incorrect menu category name
  src/configs/menu-categories.js
Labels: bug, Admin

#1395 add_field_create_promocode_to_menu_category-promocodes
  src/configs/menu-categories.js
  src/pages/promo-code/promo-code-page.js
Labels: bug, Admin

#1391 Add validation for checking if size is already created
  src/configs/error-modal-messages.js
  src/redux/sizes/sizes.operations.js
Labels: Admin

#1397 Bugfix/1387/illogical name of column
  src/configs/table-head-row-titles.js
Labels: Admin, UI

#1401 added indent to expanded tabs, refactored code in nav-menu element
  src/components/nav-menu/nav-menu.js
  src/components/nav-menu/nav-menu.styles.js
Labels: Admin, UI

#1405 Product/1374/product image adding/editing is not working
  src/components/forms/product-form/product-form.js
  src/hooks/product/use-product-validation.js
Labels: bug, Admin

#1403 Duplicate the notification about new clients questions
  src/components/nav-menu/nav-menu.js
  src/components/nav-menu/nav-menu.styles.js
Labels: Admin, UI
