Repository ita-social-projects/horondi_admin, pull requests merged in 2022-05, with the labels that each got.

#1329 Create component for sorting and filtering PromoCodes and Certificates
  src/configs/filter-labels.js
  src/consts/certificate-status.js
  src/consts/promo-code-status.js
  src/hooks/filters/use-certificate-filters.js
  src/hooks/filters/use-certificate-filters.test.js
  src/hooks/filters/use-promo-code-filters.js
  src/hooks/filters/use-promoCode-Certificate-filters.js
  src/pages/certificates/certificates-page.js
  src/pages/certificates/hooks/use-certificates.js
  src/pages/certificates/operations/certificate.queries.js
  src/pages/certificates/tests/certificates-page.spec.js
  src/pages/certificates/tests/certificates-page.variables.js
  src/pages/promo-code/operations/promo-code.queries.js
  src/pages/promo-code/promo-code-page.js
  src/utils/certificate.js
  src/utils/promo-code.js
Labels: Admin

#1334 Redesign/1275/move_links_from_business_pages_to_static_pages
  src/components/forms/business-page-form/business-page-form.js
  src/components/nav-menu/tests/nav-menu.spec.js
  src/configs/menu-categories.js
  src/configs/routes.js
  src/pages/business-pages/business-page-list.js
  src/pages/business-pages/tests/business-page-list.spec.js
  src/redux/business-pages/business-pages.actions.js
  src/redux/business-pages/business-pages.operations.js
  src/redux/business-pages/business-pages.sagas.js
  src/redux/business-pages/business-pages.types.js
  src/redux/business-pages/tests/business-pages.actions.test.js
  src/redux/business-pages/tests/business-pages.sagas.test.js
  src/redux/business-pages/tests/business-pages.variables.js
  src/routes/routes.js
Labels: Admin, UI

#1337 Fix phone number format
  src/configs/error-messages.js
  src/utils/format-phone-number.js
Labels: Admin

#1340 [Catalog] Size, Gobelens list appears only after page reload
  src/redux/material/material.sagas.js
Labels: bug, Admin

#1342 Feature/1333/worldwide delivery component
  src/configs/index.js
  src/configs/labels.js
  src/configs/orders.js
  src/configs/regexes.js
  src/pages/order-item/tabs/delivery-details/courier/courier.js
  src/pages/order-item/tabs/delivery-details/worldwide/const.js
  src/pages/order-item/tabs/delivery-details/worldwide/index.js
  src/pages/order-item/tabs/delivery-details/worldwide/tests/worldwide.spec.js
  src/pages/order-item/tabs/delivery-details/worldwide/tests/worldwide.variables.js
  src/pages/order-item/tabs/delivery-details/worldwide/worldwide.js
  src/pages/order-item/tabs/delivery-details/worldwide/worldwide.styles.js
  src/pages/order-item/tabs/delivery.js
  src/pages/order-item/tabs/tests/delivery-tests/delivery.spec.js
  src/pages/order-item/tabs/tests/delivery-tests/delivery.variables.js
  src/redux/orders/orders.operations.js
  src/services/tests/worldwide-delivery.service.spec.js
  src/services/tests/worldwide-delivery.service.variables.js
  src/services/worldwide-delivery.service.js
  src/utils/order.js
  src/validations/orders/order-form-validation.js
Labels: Admin

#1341 [Contacts] Save button doesn't work properly
  src/components/forms/back-form/back-form.js
  src/components/forms/basics-form/basics-form.js
  src/components/forms/bottom-form/bottom-form.js
  src/components/forms/closures-form/closures-form.js
  src/components/forms/comment-form/comment-form.js
  src/components/forms/contacts-form/contacts-form.js
  src/components/forms/home-page-slide-form/home-page-slide-form.js
  src/components/forms/material-form/material-form.js
  src/components/forms/model-form/model-form.js
  src/components/forms/news-form/news-form.js
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/pattern-form/tests/pattern-form.spec.js
  src/components/forms/pattern-form/tests/pattern-form.variables.js
  src/components/forms/pockets-form/pockets-form.js
  src/components/forms/position-form/position-form.js
  src/components/forms/position-form/tests/position-form.spec.js
  src/components/forms/position-form/tests/position-form.variables.js
  src/components/forms/size-form/size-form.js
  src/components/forms/straps-form/straps-form.js
Labels: Admin

#1346 remove setFieldValue in worldwide useEffect
  src/pages/order-item/tabs/delivery-details/worldwide/worldwide.js
Labels: bug, Admin

#1347 changed color of nav-menu icons
  src/components/nav-menu/nav-menu.js
  src/components/nav-menu/nav-menu.styles.js
Labels: Admin, UI, CSS
