Repository ita-social-projects/horondi_admin, pull requests merged in 2022-10, with the labels that each got.

#1450 Cant add new section in about
  src/assets/images/no-image.png
  src/components/forms/about-us-forms/about-us-section-add-form/about-us-section-add-form.js
  src/components/forms/about-us-forms/about-us-section-edit-form/about-us-section-edit-form.js
  src/components/forms/about-us-forms/operations/about-us.mutation.js
  src/components/forms/language-panel/language-panel.js
  src/components/loading-bar/loading-bar.js
  src/configs/error-modal-messages.js
  src/containers/table-container-row/table-container-row.js
  src/pages/about-us/about-us.js
  src/pages/about-us/tests/about-us.spec.js
  src/pages/about-us/tests/about-us.variables.js
  src/pages/login/login-page.js
  src/utils/about-us-helper.js
  src/validations/about-us/about-us-edit-validation.js
Labels: bug, Admin

#1474 add create promo code button
  src/configs/button-titles.js
  src/pages/promo-code/promo-code-page.js
  src/pages/promo-code/promo-code-page.styles.js
Labels: bug, Admin

#1476 bugfix/1455/fix changing quantity of products in order
  src/pages/order-item/tabs/edit-product-form/edit-product-form.js
Labels: bug, Admin

#1469 email field should be required
  package-lock.json
  src/pages/certificates/create-certificate/create-certificate.js
  src/pages/certificates/tests/create-certificate.spec.js
Labels: good first issue, Admin

#1479 refactor/1475/refactor_pockets_with_restrictions
  src/components/forms/constructor-form/constructor-list-pockets/constructor-list-pockets.js
  src/components/forms/constructor-form/constructor-list-pockets/constructor-list-pockets.styles.js
  src/components/forms/constructor-form/constructor-list-pockets/constructor-list-restrictions/constructor-list-restrictions.js
  src/components/forms/constructor-form/constructor-list-pockets/constructor-list-restrictions/constructor-list-restrictions.styles.js
  src/components/forms/constructor-form/constructor-list-pockets/constructor-list-restrictions/index.js
  src/components/forms/constructor-form/constructor-list-pockets/index.js
  src/components/forms/constructor-form/constructor-model-form.js
  src/components/forms/constructor-form/tests/constructor-list-pockets.spec.js
  src/components/forms/constructor-form/tests/constructor-list-restrictions.spec.js
  src/redux/constructor/constructor.operations.js
  src/utils/use-constructor-handlers.js
Labels: refactoring, Admin

#1477 fixed phone validation when you add order
  src/configs/regexes.js
  src/validations/orders/order-form-validation.js
Labels: bug, Admin

#1468 Delete model shoul delete products
  src/components/forms/model-form/model-form.js
  src/components/forms/size-form/size-form-accordion/size-form-accordion.js
  src/components/forms/size-form/size-form.js
  src/components/forms/size-form/tests/size-form.spec.js
  src/components/forms/size-form/tests/size-form.variables.js
  src/configs/button-titles.js
  src/configs/material-messages.js
  src/configs/messages.js
  src/hooks/filters/use-material-filters.js
  src/hooks/model-form/use-size-handlers.js
  src/hooks/model-form/use-size-handlers.spec.js
  src/hooks/model-form/use-size-handlers.variables.js
  src/pages/material/filters/filters.js
  src/pages/model/model-page.js
  src/pages/model/tests/model-page.spec.js
  src/pages/model/tests/model-page.variables.js
  src/redux/constructor/constructor.operations.js
  src/redux/products/products.operations.js
  src/utils/size.js
Labels: Admin
