Repository ita-social-projects/horondi_admin, pull requests merged in 2022-04, with the labels that each got.

#1262 Fix bug: delete product error
  src/redux/products/products.operations.js
Labels: bug, Admin

#1271 material delete validation
  src/hooks/deleteValidation/useDeleteValidation.js
Labels: bug, Admin

#1284 Bugfix/1261/fix price input and save-button behaviors
  src/components/buttons/save-button/save-button.js
  src/components/forms/back-form/back-form.js
  src/components/forms/basics-form/basics-form.js
  src/components/forms/bottom-form/bottom-form.js
  src/components/forms/category-form/category-form.js
  src/components/forms/comment-form/comment-form.js
  src/components/forms/contacts-form/contacts-form.js
  src/components/forms/header-form/header-form.js
  src/components/forms/home-page-slide-form/home-page-slide-form.js
  src/components/forms/material-form/material-form.js
  src/components/forms/model-form/model-form.js
  src/components/forms/model-form/tests/model-form.spec.js
  src/components/forms/news-form/news-form.js
  src/components/forms/news-form/tests/news-form.test.js
  src/components/forms/pattern-form/pattern-form.js
  src/components/forms/pockets-form/pockets-form.js
  src/components/forms/position-form/position-form.js
  src/components/forms/reply-comment-form/reply-comment-form.js
  src/components/forms/size-form/size-form.js
  src/components/forms/straps-form/straps-form.js
  src/components/forms/user-form/user-form.js
  src/containers/additional-price-container/additional-price-container.js
  src/hooks/forms/use-changed-values-checker.js
  src/utils/additionalPrice-helper.js
Labels: bug, Admin

#1293 handle custom backend error
  src/redux/pattern/pattern.operations.js
Labels: bug, Admin

#1290 fix bug with button
  src/hooks/filters/use-basic-filters.js
  src/redux/basics/basics.actions.js
  src/redux/basics/basics.reducer.js
  src/redux/basics/basics.types.js
  src/redux/basics/tests/basics.actions.test.js
Labels: bug, Admin

#1299 save button works
  src/configs/regexes.js
Labels: bug, Admin

#1287 fixed UserRole config
  src/configs/index.js
Labels: bug, Admin

#1294 Bugfix/1277/registered users statistic does not changed
  src/pages/statistic/statistic-page.js
Labels: bug, Admin

#1295 fix avatar on user tab list
  src/pages/users/components/user-tab/user-tab.js
  src/redux/users/users.operations.js
Labels: bug, Admin

#1298 Fixed undefined-data, unique keys and colors in StatisticDoughnut
  src/configs/index.js
  src/configs/titles.js
  src/pages/statistic/statistic-doughnut/legends-list/legends-list.js
Labels: bug, Admin

#1305 added status 'Planned' to promocodes
  src/configs/orders.js
  src/pages/promo-code/promo-code-page.js
  src/pages/promo-code/tests/promo-code-page.variables.js
Labels: bug, Admin

#1309 Fix bug with certificates displayed
  src/pages/certificates/certificates-page.js
Labels: Admin, Hotfix

#1296 fixed bug with allowing add product without a photo an some other fixes
  src/components/forms/product-form/product-form.js
  src/components/forms/product-form/tests/product-form.spec.js
  src/configs/error-messages.js
  src/containers/product-info-container/product-info-container.js
  src/containers/product-species-container/product-species-container.js
  src/hooks/product/use-product-validation.js
  src/pages/products/product-add/product-add-images/product-add-images.js
Labels: bug, Admin

#1311 fixed regexp
  src/configs/form-regexp.js
Labels: bug, Admin

#1314 pass fields for tranlations_keys
  src/pages/home-page-slides/slides-order/slides-order.js
Labels: bug, Admin

#1312 [Users] Remove table with products when on users page
  src/configs/error-modal-messages.js
  src/pages/users/components/admin-tab/admin-tab.js
  src/pages/users/components/admin-tab/tests/admin-page.test.js
  src/pages/users/components/admin-tab/tests/variables.js
  src/pages/users/components/user-tab/tests/user-page.test.js
  src/pages/users/components/user-tab/tests/variables.js
  src/pages/users/components/user-tab/user-tab.js
  src/pages/users/components/users-filters/UsersFilters.js
Labels: Admin

#1318 add limit counts
  src/pages/certificates/checkBoxes/checkBoxes.js
Labels: Admin, functional

#1327 Wrong input validation on promocode creation.
  src/configs/error-messages.js
  src/configs/form-regexp.js
  src/validations/promo-code/promo-code-validation.js
Labels: Admin, UI

#1289 Delete and update certificates
  package-lock.json
  package.json
  src/configs/messages.js
  src/configs/titles.js
  src/pages/certificates/certificates-page.js
  src/pages/certificates/hooks/use-certificates.js
  src/pages/certificates/operations/certificate.mutation.js
  src/pages/certificates/tests/certificates-page.spec.js
  src/pages/certificates/tests/certificates-page.variables.js
  src/pages/certificates/tests/use-certificates.spec.js
  src/utils/use-success-snackbar.js
Labels: Admin, feature
