Repository ita-social-projects/horondi_admin, pull requests merged in 2022-03, with the labels that each got.

#1226 Refactor/1157/create a page certificates information
  src/configs/button-titles.js
  src/configs/messages.js
  src/configs/statuses.js
  src/configs/table-head-row-titles.js
  src/configs/titles.js
  src/pages/certificates/certificate/certificate.js
  src/pages/certificates/certificate/certificate.styles.js
  src/pages/certificates/certificates-page.js
  src/pages/certificates/img/certificate.svg
  src/pages/certificates/index.js
  src/pages/certificates/operations/certificate.queries.js
  src/pages/certificates/status/certificate-status-styles.js
  src/pages/certificates/status/status.js
  src/pages/certificates/tests/certificates-page.spec.js
  src/pages/certificates/tests/certificates-page.variables.js
  src/routes/routes.js
Labels: refactoring, Admin

#1257 fix uaNameCreation regexp to properly write color pattern
  src/configs/form-regexp.js
Labels: good first issue, Admin

#1260 fixed error text color
  src/containers/additional-price-container/additional-price-container.styles.js
Labels: good first issue, Admin, UI

#1258 Changed color of nav-menu icons
  package-lock.json
  src/components/nav-bar/icons.js
  src/components/nav-menu/nav-menu.js
  src/components/nav-menu/nav-menu.styles.js
Labels: good first issue, Admin, UI, CSS

#1268 fixed displayed photo of the straps
  src/pages/straps/straps-page.js
Labels: bug, Admin

#1270 Fix columns naming according to their appointment
  src/configs/table-head-row-titles.js
Labels: Admin, functional

#1283 Fix columns naming according to their appointment
  src/configs/table-head-row-titles.js
Labels: Admin, functional
