Repository ita-social-projects/horondi_admin, pull requests merged in 2022-08, with the labels that each got.

#1427 Add changes in About materials to the Recent changes
  src/consts/history-events.js
  src/pages/material/material-about-details.js
  src/pages/material/tests/material-about-details.spec.js
  src/pages/material/tests/material-about.variables.js
Labels: Admin

#1433 Added posibility for admin to add promocode
  src/configs/button-titles.js
  src/configs/orders.js
  src/pages/order-item/tabs/add-product-form/add-product-form.js
  src/pages/order-item/tabs/add-product-form/add-product-form.styles.js
  src/pages/order-item/tabs/edit-product-form/edit-product-form.js
  src/pages/order-item/tabs/products.js
  src/pages/order-item/tabs/tests/add-product-form-tests/add-product-form.spec.js
  src/pages/order-item/tabs/tests/add-product-form-tests/add-product-form.variables.js
  src/pages/order-item/tabs/tests/edit-product-form-tests/edit-product-form.spec.js
  src/pages/order-item/tabs/tests/edit-product-form-tests/edit-product-form.variables.js
  src/pages/order-item/tabs/tests/products-tests/products.spec.js
  src/pages/order-item/tabs/tests/products-tests/products.variables.js
  src/pages/promo-code/operations/promo-code.queries.js
  src/redux/orders/orders.sagas.js
  src/utils/order.js
  src/utils/order.values.js
  src/utils/tests/order.test.js
  src/utils/tests/order.variables.js
Labels: Admin, feature

#1436 Bugfix/1434/Add order without user
  src/utils/order.js
Labels: bug, Admin

#1438 Feature/1435/Validation errors for order addition
  src/configs/error-messages.js
  src/pages/order-item/order-item.js
  src/pages/order-item/order-item.styles.js
  src/pages/order-item/tabs/add-product-form/add-product-form.js
  src/pages/order-item/tabs/add-product-form/add-product-form.styles.js
  src/pages/order-item/tabs/delivery-details/courier/courier.js
  src/pages/order-item/tabs/delivery-details/nova-post/nova-post.js
  src/pages/order-item/tabs/delivery-details/nova-post/tests/nova-post.spec.js
  src/pages/order-item/tabs/delivery-details/nova-post/tests/nova-post.variables.js
  src/pages/order-item/tabs/delivery-details/ukrpost/tests/ukrpost.spec.js
  src/pages/order-item/tabs/delivery-details/ukrpost/tests/ukrpost.variables.js
  src/pages/order-item/tabs/delivery-details/ukrpost/ukrpost.js
  src/pages/order-item/tabs/delivery-details/worldwide/tests/worldwide.spec.js
  src/pages/order-item/tabs/delivery-details/worldwide/tests/worldwide.variables.js
  src/pages/order-item/tabs/delivery-details/worldwide/worldwide.js
  src/pages/order-item/tabs/delivery-details/worldwide/worldwide.styles.js
  src/pages/order-item/tabs/delivery.js
  src/pages/order-item/tabs/general.js
  src/pages/order-item/tabs/products.js
  src/pages/order-item/tabs/recipient.js
  src/pages/order-item/tabs/tests/add-product-form-tests/add-product-form.spec.js
  src/pages/order-item/tabs/tests/add-product-form-tests/add-product-form.variables.js
  src/pages/order-item/tabs/tests/delivery-tests/delivery.spec.js
  src/pages/order-item/tabs/tests/delivery-tests/delivery.variables.js
  src/pages/order-item/tabs/tests/general-tests/general.spec.js
  src/pages/order-item/tabs/tests/general-tests/general.variables.js
  src/pages/order-item/tabs/tests/products-tests/products.spec.js
  src/pages/order-item/tabs/tests/products-tests/products.variables.js
  src/pages/order-item/tabs/tests/recipient-tests/recipient.spec.js
  src/pages/order-item/tabs/tests/recipient-tests/recipient.variables.js
  src/utils/form-error-validation.js
  src/utils/order.js
  src/validations/orders/order-form-validation.js
Labels: Admin, feature

#1440 When admin adding certificate wrong date
  src/pages/certificates/create-certificate/create-certificate.js
Labels: bug, Admin

#1442 Bugix/1441/Fix materials query
  src/redux/material/material.operations.js
  src/redux/products/products.operations.js
Labels: bug, Admin
